/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetTaskKnowledgeParams,
  HTTPValidationError,
  ListTaskKnowledgeResponse,
  ListTaskResponse,
  ListTasksParams,
  TaskKnowledgeResponse,
  TaskResultResponse,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List all tasks.

Parameters
----------
ctx : ProjectContext
    The project context with user and project information.
service : TaskService
    The task service instance.
backend : str | None
    Optional backend name to filter tasks by.

Returns
-------
ListTaskResponse
    The list of tasks.
 * @summary List all tasks
 */
export const listTasks = (
  params?: ListTasksParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListTaskResponse>(
    { url: `/tasks`, method: "GET", params, signal },
    options,
  );
};

export const getListTasksQueryKey = (params?: ListTasksParams) => {
  return [`/tasks`, ...(params ? [params] : [])] as const;
};

export const getListTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = HTTPValidationError,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTasksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasks>>> = ({
    signal,
  }) => listTasks(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTasks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListTasksQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTasks>>
>;
export type ListTasksQueryError = HTTPValidationError;

export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = HTTPValidationError,
>(
  params: undefined | ListTasksParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasks>>,
          TError,
          Awaited<ReturnType<typeof listTasks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = HTTPValidationError,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasks>>,
          TError,
          Awaited<ReturnType<typeof listTasks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = HTTPValidationError,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List all tasks
 */

export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = HTTPValidationError,
>(
  params?: ListTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTasks>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListTasksQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get task result by task_id.

Parameters
----------
task_id : str
    The task ID to search for.
ctx : ProjectContext
    The project context with user and project information.
service : TaskService
    The task service instance.

Returns
-------
TaskResultResponse
    The task result information including figure paths.
 * @summary Get task result by task ID
 */
export const getTaskResult = (
  taskId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskResultResponse>(
    { url: `/tasks/${taskId}/result`, method: "GET", signal },
    options,
  );
};

export const getGetTaskResultQueryKey = (taskId?: string) => {
  return [`/tasks/${taskId}/result`] as const;
};

export const getGetTaskResultQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskResult>>,
  TError = HTTPValidationError,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTaskResult>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaskResultQueryKey(taskId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskResult>>> = ({
    signal,
  }) => getTaskResult(taskId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!taskId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskResult>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTaskResultQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTaskResult>>
>;
export type GetTaskResultQueryError = HTTPValidationError;

export function useGetTaskResult<
  TData = Awaited<ReturnType<typeof getTaskResult>>,
  TError = HTTPValidationError,
>(
  taskId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTaskResult>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskResult>>,
          TError,
          Awaited<ReturnType<typeof getTaskResult>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTaskResult<
  TData = Awaited<ReturnType<typeof getTaskResult>>,
  TError = HTTPValidationError,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTaskResult>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskResult>>,
          TError,
          Awaited<ReturnType<typeof getTaskResult>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTaskResult<
  TData = Awaited<ReturnType<typeof getTaskResult>>,
  TError = HTTPValidationError,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTaskResult>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get task result by task ID
 */

export function useGetTaskResult<
  TData = Awaited<ReturnType<typeof getTaskResult>>,
  TError = HTTPValidationError,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTaskResult>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTaskResultQueryOptions(taskId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List all available task knowledge entries with summary info.
 * @summary List all task knowledge entries
 */
export const listTaskKnowledge = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListTaskKnowledgeResponse>(
    { url: `/task-knowledge`, method: "GET", signal },
    options,
  );
};

export const getListTaskKnowledgeQueryKey = () => {
  return [`/task-knowledge`] as const;
};

export const getListTaskKnowledgeQueryOptions = <
  TData = Awaited<ReturnType<typeof listTaskKnowledge>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listTaskKnowledge>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTaskKnowledgeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listTaskKnowledge>>
  > = ({ signal }) => listTaskKnowledge(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTaskKnowledge>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListTaskKnowledgeQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTaskKnowledge>>
>;
export type ListTaskKnowledgeQueryError = unknown;

export function useListTaskKnowledge<
  TData = Awaited<ReturnType<typeof listTaskKnowledge>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaskKnowledge>>,
          TError,
          Awaited<ReturnType<typeof listTaskKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListTaskKnowledge<
  TData = Awaited<ReturnType<typeof listTaskKnowledge>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaskKnowledge>>,
          TError,
          Awaited<ReturnType<typeof listTaskKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListTaskKnowledge<
  TData = Awaited<ReturnType<typeof listTaskKnowledge>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List all task knowledge entries
 */

export function useListTaskKnowledge<
  TData = Awaited<ReturnType<typeof listTaskKnowledge>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListTaskKnowledgeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get raw markdown content for a task knowledge entry.

Returns the index.md content with image references replaced
by inline base64 data URIs for self-contained rendering.
 * @summary Get raw markdown for a task knowledge entry
 */
export const getTaskKnowledgeMarkdown = (
  taskName: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/tasks/${taskName}/knowledge/markdown`, method: "GET", signal },
    options,
  );
};

export const getGetTaskKnowledgeMarkdownQueryKey = (taskName?: string) => {
  return [`/tasks/${taskName}/knowledge/markdown`] as const;
};

export const getGetTaskKnowledgeMarkdownQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTaskKnowledgeMarkdownQueryKey(taskName);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>
  > = ({ signal }) =>
    getTaskKnowledgeMarkdown(taskName, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!taskName,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTaskKnowledgeMarkdownQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>
>;
export type GetTaskKnowledgeMarkdownQueryError = HTTPValidationError;

export function useGetTaskKnowledgeMarkdown<
  TData = Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
          TError,
          Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTaskKnowledgeMarkdown<
  TData = Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
          TError,
          Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTaskKnowledgeMarkdown<
  TData = Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get raw markdown for a task knowledge entry
 */

export function useGetTaskKnowledgeMarkdown<
  TData = Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledgeMarkdown>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTaskKnowledgeMarkdownQueryOptions(
    taskName,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get structured domain knowledge for a calibration task.

Returns LLM-oriented knowledge including physical principles,
expected behavior, evaluation criteria, and failure modes.

Parameters
----------
task_name : str
    The task name (e.g. "CheckT1", "CheckRabi").
service : TaskService
    The task service instance.
backend : str
    The backend name (default "qubex").

Returns
-------
TaskKnowledgeResponse
    Structured task knowledge.
 * @summary Get task knowledge for LLM analysis
 */
export const getTaskKnowledge = (
  taskName: string,
  params?: GetTaskKnowledgeParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskKnowledgeResponse>(
    { url: `/tasks/${taskName}/knowledge`, method: "GET", params, signal },
    options,
  );
};

export const getGetTaskKnowledgeQueryKey = (
  taskName?: string,
  params?: GetTaskKnowledgeParams,
) => {
  return [`/tasks/${taskName}/knowledge`, ...(params ? [params] : [])] as const;
};

export const getGetTaskKnowledgeQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskKnowledge>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  params?: GetTaskKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTaskKnowledgeQueryKey(taskName, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTaskKnowledge>>
  > = ({ signal }) =>
    getTaskKnowledge(taskName, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!taskName,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskKnowledge>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTaskKnowledgeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTaskKnowledge>>
>;
export type GetTaskKnowledgeQueryError = HTTPValidationError;

export function useGetTaskKnowledge<
  TData = Awaited<ReturnType<typeof getTaskKnowledge>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  params: undefined | GetTaskKnowledgeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskKnowledge>>,
          TError,
          Awaited<ReturnType<typeof getTaskKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTaskKnowledge<
  TData = Awaited<ReturnType<typeof getTaskKnowledge>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  params?: GetTaskKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskKnowledge>>,
          TError,
          Awaited<ReturnType<typeof getTaskKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTaskKnowledge<
  TData = Awaited<ReturnType<typeof getTaskKnowledge>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  params?: GetTaskKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get task knowledge for LLM analysis
 */

export function useGetTaskKnowledge<
  TData = Awaited<ReturnType<typeof getTaskKnowledge>>,
  TError = HTTPValidationError,
>(
  taskName: string,
  params?: GetTaskKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTaskKnowledgeQueryOptions(
    taskName,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
