/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  IssueKnowledgeResponse,
  IssueKnowledgeUpdate,
  ListIssueKnowledgeParams,
  ListIssueKnowledgeResponse,
  SuccessResponse,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List issue-derived knowledge cases with optional filters.
 * @summary List knowledge cases
 */
export const listIssueKnowledge = (
  params?: ListIssueKnowledgeParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListIssueKnowledgeResponse>(
    { url: `/issue-knowledge`, method: "GET", params, signal },
    options,
  );
};

export const getListIssueKnowledgeQueryKey = (
  params?: ListIssueKnowledgeParams,
) => {
  return [`/issue-knowledge`, ...(params ? [params] : [])] as const;
};

export const getListIssueKnowledgeQueryOptions = <
  TData = Awaited<ReturnType<typeof listIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  params?: ListIssueKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listIssueKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListIssueKnowledgeQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listIssueKnowledge>>
  > = ({ signal }) => listIssueKnowledge(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listIssueKnowledge>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListIssueKnowledgeQueryResult = NonNullable<
  Awaited<ReturnType<typeof listIssueKnowledge>>
>;
export type ListIssueKnowledgeQueryError = HTTPValidationError;

export function useListIssueKnowledge<
  TData = Awaited<ReturnType<typeof listIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  params: undefined | ListIssueKnowledgeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listIssueKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listIssueKnowledge>>,
          TError,
          Awaited<ReturnType<typeof listIssueKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListIssueKnowledge<
  TData = Awaited<ReturnType<typeof listIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  params?: ListIssueKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listIssueKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listIssueKnowledge>>,
          TError,
          Awaited<ReturnType<typeof listIssueKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListIssueKnowledge<
  TData = Awaited<ReturnType<typeof listIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  params?: ListIssueKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listIssueKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List knowledge cases
 */

export function useListIssueKnowledge<
  TData = Awaited<ReturnType<typeof listIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  params?: ListIssueKnowledgeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listIssueKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListIssueKnowledgeQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a single knowledge case by ID.
 * @summary Get a knowledge case
 */
export const getIssueKnowledge = (
  knowledgeId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<IssueKnowledgeResponse>(
    { url: `/issue-knowledge/${knowledgeId}`, method: "GET", signal },
    options,
  );
};

export const getGetIssueKnowledgeQueryKey = (knowledgeId?: string) => {
  return [`/issue-knowledge/${knowledgeId}`] as const;
};

export const getGetIssueKnowledgeQueryOptions = <
  TData = Awaited<ReturnType<typeof getIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  knowledgeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssueKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetIssueKnowledgeQueryKey(knowledgeId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getIssueKnowledge>>
  > = ({ signal }) => getIssueKnowledge(knowledgeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!knowledgeId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getIssueKnowledge>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetIssueKnowledgeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIssueKnowledge>>
>;
export type GetIssueKnowledgeQueryError = HTTPValidationError;

export function useGetIssueKnowledge<
  TData = Awaited<ReturnType<typeof getIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  knowledgeId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssueKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueKnowledge>>,
          TError,
          Awaited<ReturnType<typeof getIssueKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetIssueKnowledge<
  TData = Awaited<ReturnType<typeof getIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  knowledgeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssueKnowledge>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueKnowledge>>,
          TError,
          Awaited<ReturnType<typeof getIssueKnowledge>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetIssueKnowledge<
  TData = Awaited<ReturnType<typeof getIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  knowledgeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssueKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a knowledge case
 */

export function useGetIssueKnowledge<
  TData = Awaited<ReturnType<typeof getIssueKnowledge>>,
  TError = HTTPValidationError,
>(
  knowledgeId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIssueKnowledge>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetIssueKnowledgeQueryOptions(knowledgeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a knowledge draft's content. Only drafts can be edited.
 * @summary Update a knowledge draft
 */
export const updateIssueKnowledge = (
  knowledgeId: string,
  issueKnowledgeUpdate: IssueKnowledgeUpdate,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<IssueKnowledgeResponse>(
    {
      url: `/issue-knowledge/${knowledgeId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: issueKnowledgeUpdate,
    },
    options,
  );
};

export const getUpdateIssueKnowledgeMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateIssueKnowledge>>,
    TError,
    { knowledgeId: string; data: IssueKnowledgeUpdate },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateIssueKnowledge>>,
  TError,
  { knowledgeId: string; data: IssueKnowledgeUpdate },
  TContext
> => {
  const mutationKey = ["updateIssueKnowledge"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateIssueKnowledge>>,
    { knowledgeId: string; data: IssueKnowledgeUpdate }
  > = (props) => {
    const { knowledgeId, data } = props ?? {};

    return updateIssueKnowledge(knowledgeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateIssueKnowledgeMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateIssueKnowledge>>
>;
export type UpdateIssueKnowledgeMutationBody = IssueKnowledgeUpdate;
export type UpdateIssueKnowledgeMutationError = HTTPValidationError;

/**
 * @summary Update a knowledge draft
 */
export const useUpdateIssueKnowledge = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateIssueKnowledge>>,
      TError,
      { knowledgeId: string; data: IssueKnowledgeUpdate },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateIssueKnowledge>>,
  TError,
  { knowledgeId: string; data: IssueKnowledgeUpdate },
  TContext
> => {
  const mutationOptions = getUpdateIssueKnowledgeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a knowledge case.
 * @summary Delete a knowledge case
 */
export const deleteIssueKnowledge = (
  knowledgeId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SuccessResponse>(
    { url: `/issue-knowledge/${knowledgeId}`, method: "DELETE" },
    options,
  );
};

export const getDeleteIssueKnowledgeMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteIssueKnowledge>>,
    TError,
    { knowledgeId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteIssueKnowledge>>,
  TError,
  { knowledgeId: string },
  TContext
> => {
  const mutationKey = ["deleteIssueKnowledge"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteIssueKnowledge>>,
    { knowledgeId: string }
  > = (props) => {
    const { knowledgeId } = props ?? {};

    return deleteIssueKnowledge(knowledgeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteIssueKnowledgeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteIssueKnowledge>>
>;

export type DeleteIssueKnowledgeMutationError = HTTPValidationError;

/**
 * @summary Delete a knowledge case
 */
export const useDeleteIssueKnowledge = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteIssueKnowledge>>,
      TError,
      { knowledgeId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteIssueKnowledge>>,
  TError,
  { knowledgeId: string },
  TContext
> => {
  const mutationOptions = getDeleteIssueKnowledgeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Generate an AI knowledge draft from a closed issue thread.
 * @summary Generate knowledge draft from issue
 */
export const extractIssueKnowledge = (
  issueId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<IssueKnowledgeResponse>(
    { url: `/issues/${issueId}/extract-knowledge`, method: "POST", signal },
    options,
  );
};

export const getExtractIssueKnowledgeMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof extractIssueKnowledge>>,
    TError,
    { issueId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof extractIssueKnowledge>>,
  TError,
  { issueId: string },
  TContext
> => {
  const mutationKey = ["extractIssueKnowledge"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof extractIssueKnowledge>>,
    { issueId: string }
  > = (props) => {
    const { issueId } = props ?? {};

    return extractIssueKnowledge(issueId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExtractIssueKnowledgeMutationResult = NonNullable<
  Awaited<ReturnType<typeof extractIssueKnowledge>>
>;

export type ExtractIssueKnowledgeMutationError = HTTPValidationError;

/**
 * @summary Generate knowledge draft from issue
 */
export const useExtractIssueKnowledge = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof extractIssueKnowledge>>,
      TError,
      { issueId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof extractIssueKnowledge>>,
  TError,
  { issueId: string },
  TContext
> => {
  const mutationOptions = getExtractIssueKnowledgeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Approve a knowledge draft for inclusion in task knowledge.
 * @summary Approve a knowledge draft
 */
export const approveIssueKnowledge = (
  knowledgeId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<IssueKnowledgeResponse>(
    { url: `/issue-knowledge/${knowledgeId}/approve`, method: "PATCH" },
    options,
  );
};

export const getApproveIssueKnowledgeMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approveIssueKnowledge>>,
    TError,
    { knowledgeId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof approveIssueKnowledge>>,
  TError,
  { knowledgeId: string },
  TContext
> => {
  const mutationKey = ["approveIssueKnowledge"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approveIssueKnowledge>>,
    { knowledgeId: string }
  > = (props) => {
    const { knowledgeId } = props ?? {};

    return approveIssueKnowledge(knowledgeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApproveIssueKnowledgeMutationResult = NonNullable<
  Awaited<ReturnType<typeof approveIssueKnowledge>>
>;

export type ApproveIssueKnowledgeMutationError = HTTPValidationError;

/**
 * @summary Approve a knowledge draft
 */
export const useApproveIssueKnowledge = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approveIssueKnowledge>>,
      TError,
      { knowledgeId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof approveIssueKnowledge>>,
  TError,
  { knowledgeId: string },
  TContext
> => {
  const mutationOptions = getApproveIssueKnowledgeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Reject a knowledge draft.
 * @summary Reject a knowledge draft
 */
export const rejectIssueKnowledge = (
  knowledgeId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<IssueKnowledgeResponse>(
    { url: `/issue-knowledge/${knowledgeId}/reject`, method: "PATCH" },
    options,
  );
};

export const getRejectIssueKnowledgeMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rejectIssueKnowledge>>,
    TError,
    { knowledgeId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rejectIssueKnowledge>>,
  TError,
  { knowledgeId: string },
  TContext
> => {
  const mutationKey = ["rejectIssueKnowledge"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rejectIssueKnowledge>>,
    { knowledgeId: string }
  > = (props) => {
    const { knowledgeId } = props ?? {};

    return rejectIssueKnowledge(knowledgeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RejectIssueKnowledgeMutationResult = NonNullable<
  Awaited<ReturnType<typeof rejectIssueKnowledge>>
>;

export type RejectIssueKnowledgeMutationError = HTTPValidationError;

/**
 * @summary Reject a knowledge draft
 */
export const useRejectIssueKnowledge = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rejectIssueKnowledge>>,
      TError,
      { knowledgeId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof rejectIssueKnowledge>>,
  TError,
  { knowledgeId: string },
  TContext
> => {
  const mutationOptions = getRejectIssueKnowledgeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
