/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChipDatesResponse,
  ChipResponse,
  CouplingResponse,
  CreateChipRequest,
  HTTPValidationError,
  ListChipCouplingsParams,
  ListChipQubitsParams,
  ListChipsResponse,
  ListCouplingsResponse,
  ListMuxResponse,
  ListQubitsResponse,
  MetricHeatmapResponse,
  MetricsSummaryResponse,
  MuxDetailResponse,
  QubitResponse,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List all chips with summary information.

Returns chip metadata (id, size, topology, qubit/coupling counts).
For detailed qubit/coupling data, use the dedicated endpoints.
 * @summary List all chips
 */
export const listChips = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListChipsResponse>(
    { url: `/chips`, method: "GET", signal },
    options,
  );
};

export const getListChipsQueryKey = () => {
  return [`/chips`] as const;
};

export const getListChipsQueryOptions = <
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = HTTPValidationError,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListChipsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listChips>>> = ({
    signal,
  }) => listChips(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listChips>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListChipsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listChips>>
>;
export type ListChipsQueryError = HTTPValidationError;

export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = HTTPValidationError,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChips>>,
          TError,
          Awaited<ReturnType<typeof listChips>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChips>>,
          TError,
          Awaited<ReturnType<typeof listChips>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List all chips
 */

export function useListChips<
  TData = Awaited<ReturnType<typeof listChips>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChips>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListChipsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a new chip in the current project.

Parameters
----------
request : CreateChipRequest
    Chip creation request containing chip_id and size
ctx : ProjectContext
    Project context with owner permission

Returns
-------
ChipResponse
    Created chip information

Raises
------
HTTPException
    If chip_id already exists or size is invalid
 * @summary Create a new chip
 */
export const createChip = (
  createChipRequest: CreateChipRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChipResponse>(
    {
      url: `/chips`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createChipRequest,
      signal,
    },
    options,
  );
};

export const getCreateChipMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChip>>,
    TError,
    { data: CreateChipRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChip>>,
  TError,
  { data: CreateChipRequest },
  TContext
> => {
  const mutationKey = ["createChip"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChip>>,
    { data: CreateChipRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createChip(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateChipMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChip>>
>;
export type CreateChipMutationBody = CreateChipRequest;
export type CreateChipMutationError = HTTPValidationError;

/**
 * @summary Create a new chip
 */
export const useCreateChip = <TError = HTTPValidationError, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createChip>>,
      TError,
      { data: CreateChipRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createChip>>,
  TError,
  { data: CreateChipRequest },
  TContext
> => {
  const mutationOptions = getCreateChipMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Fetch available dates for a chip from execution counter.

Parameters
----------
chip_id : str
    ID of the chip
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
ChipDatesResponse
    List of available dates
 * @summary Get available dates for a chip
 */
export const getChipDates = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChipDatesResponse>(
    { url: `/chips/${chipId}/dates`, method: "GET", signal },
    options,
  );
};

export const getGetChipDatesQueryKey = (chipId?: string) => {
  return [`/chips/${chipId}/dates`] as const;
};

export const getGetChipDatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getChipDates>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipDates>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChipDatesQueryKey(chipId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChipDates>>> = ({
    signal,
  }) => getChipDates(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChipDates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetChipDatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChipDates>>
>;
export type GetChipDatesQueryError = HTTPValidationError;

export function useGetChipDates<
  TData = Awaited<ReturnType<typeof getChipDates>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipDates>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipDates>>,
          TError,
          Awaited<ReturnType<typeof getChipDates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetChipDates<
  TData = Awaited<ReturnType<typeof getChipDates>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipDates>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipDates>>,
          TError,
          Awaited<ReturnType<typeof getChipDates>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChipDates<
  TData = Awaited<ReturnType<typeof getChipDates>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipDates>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get available dates for a chip
 */

export function useGetChipDates<
  TData = Awaited<ReturnType<typeof getChipDates>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipDates>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetChipDatesQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get the multiplexer details.

Parameters
----------
chip_id : str
    ID of the chip
mux_id : int
    ID of the multiplexer
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
MuxDetailResponse
    Multiplexer details
 * @summary Get multiplexer details
 */
export const getChipMux = (
  chipId: string,
  muxId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MuxDetailResponse>(
    { url: `/chips/${chipId}/muxes/${muxId}`, method: "GET", signal },
    options,
  );
};

export const getGetChipMuxQueryKey = (chipId?: string, muxId?: number) => {
  return [`/chips/${chipId}/muxes/${muxId}`] as const;
};

export const getGetChipMuxQueryOptions = <
  TData = Awaited<ReturnType<typeof getChipMux>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipMux>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChipMuxQueryKey(chipId, muxId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChipMux>>> = ({
    signal,
  }) => getChipMux(chipId, muxId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && muxId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChipMux>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetChipMuxQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChipMux>>
>;
export type GetChipMuxQueryError = HTTPValidationError;

export function useGetChipMux<
  TData = Awaited<ReturnType<typeof getChipMux>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  muxId: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipMux>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipMux>>,
          TError,
          Awaited<ReturnType<typeof getChipMux>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetChipMux<
  TData = Awaited<ReturnType<typeof getChipMux>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipMux>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipMux>>,
          TError,
          Awaited<ReturnType<typeof getChipMux>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChipMux<
  TData = Awaited<ReturnType<typeof getChipMux>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipMux>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get multiplexer details
 */

export function useGetChipMux<
  TData = Awaited<ReturnType<typeof getChipMux>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  muxId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipMux>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetChipMuxQueryOptions(chipId, muxId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List all multiplexers for a chip.

Parameters
----------
chip_id : str
    ID of the chip
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
ListMuxResponse
    List of multiplexer details
 * @summary List all multiplexers for a chip
 */
export const listChipMuxes = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListMuxResponse>(
    { url: `/chips/${chipId}/muxes`, method: "GET", signal },
    options,
  );
};

export const getListChipMuxesQueryKey = (chipId?: string) => {
  return [`/chips/${chipId}/muxes`] as const;
};

export const getListChipMuxesQueryOptions = <
  TData = Awaited<ReturnType<typeof listChipMuxes>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipMuxes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListChipMuxesQueryKey(chipId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listChipMuxes>>> = ({
    signal,
  }) => listChipMuxes(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listChipMuxes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListChipMuxesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listChipMuxes>>
>;
export type ListChipMuxesQueryError = HTTPValidationError;

export function useListChipMuxes<
  TData = Awaited<ReturnType<typeof listChipMuxes>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipMuxes>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipMuxes>>,
          TError,
          Awaited<ReturnType<typeof listChipMuxes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListChipMuxes<
  TData = Awaited<ReturnType<typeof listChipMuxes>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipMuxes>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipMuxes>>,
          TError,
          Awaited<ReturnType<typeof listChipMuxes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListChipMuxes<
  TData = Awaited<ReturnType<typeof listChipMuxes>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipMuxes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List all multiplexers for a chip
 */

export function useListChipMuxes<
  TData = Awaited<ReturnType<typeof listChipMuxes>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipMuxes>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListChipMuxesQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get chip details including metadata and counts.

Returns chip metadata (size, topology, qubit/coupling counts).
For detailed qubit/coupling data, use the dedicated endpoints.

Parameters
----------
chip_id : str
    ID of the chip
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
ChipResponse
    Chip details
 * @summary Get chip details
 */
export const getChip = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ChipResponse>(
    { url: `/chips/${chipId}`, method: "GET", signal },
    options,
  );
};

export const getGetChipQueryKey = (chipId?: string) => {
  return [`/chips/${chipId}`] as const;
};

export const getGetChipQueryOptions = <
  TData = Awaited<ReturnType<typeof getChip>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChip>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChipQueryKey(chipId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChip>>> = ({
    signal,
  }) => getChip(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getChip>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData>;
  };
};

export type GetChipQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChip>>
>;
export type GetChipQueryError = HTTPValidationError;

export function useGetChip<
  TData = Awaited<ReturnType<typeof getChip>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChip>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChip>>,
          TError,
          Awaited<ReturnType<typeof getChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetChip<
  TData = Awaited<ReturnType<typeof getChip>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChip>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChip>>,
          TError,
          Awaited<ReturnType<typeof getChip>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChip<
  TData = Awaited<ReturnType<typeof getChip>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChip>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get chip details
 */

export function useGetChip<
  TData = Awaited<ReturnType<typeof getChip>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChip>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetChipQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List qubits for a chip with pagination.

Retrieves qubit data from the separate QubitDocument collection.
Supports filtering by specific qubit IDs.

Parameters
----------
chip_id : str
    ID of the chip
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations
limit : int
    Maximum number of qubits to return (default 50, max 256)
offset : int
    Number of qubits to skip for pagination
qids : list[str] | None
    Optional list of specific qubit IDs to fetch

Returns
-------
ListQubitsResponse
    List of qubits with pagination info
 * @summary List qubits for a chip
 */
export const listChipQubits = (
  chipId: string,
  params?: ListChipQubitsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListQubitsResponse>(
    { url: `/chips/${chipId}/qubits`, method: "GET", params, signal },
    options,
  );
};

export const getListChipQubitsQueryKey = (
  chipId?: string,
  params?: ListChipQubitsParams,
) => {
  return [`/chips/${chipId}/qubits`, ...(params ? [params] : [])] as const;
};

export const getListChipQubitsQueryOptions = <
  TData = Awaited<ReturnType<typeof listChipQubits>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipQubitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipQubits>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListChipQubitsQueryKey(chipId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listChipQubits>>> = ({
    signal,
  }) => listChipQubits(chipId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listChipQubits>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListChipQubitsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listChipQubits>>
>;
export type ListChipQubitsQueryError = HTTPValidationError;

export function useListChipQubits<
  TData = Awaited<ReturnType<typeof listChipQubits>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params: undefined | ListChipQubitsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipQubits>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipQubits>>,
          TError,
          Awaited<ReturnType<typeof listChipQubits>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListChipQubits<
  TData = Awaited<ReturnType<typeof listChipQubits>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipQubitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipQubits>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipQubits>>,
          TError,
          Awaited<ReturnType<typeof listChipQubits>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListChipQubits<
  TData = Awaited<ReturnType<typeof listChipQubits>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipQubitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipQubits>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List qubits for a chip
 */

export function useListChipQubits<
  TData = Awaited<ReturnType<typeof listChipQubits>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipQubitsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listChipQubits>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListChipQubitsQueryOptions(chipId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a single qubit by ID.

This is 10-18x faster than fetching the full chip and extracting one qubit.

Parameters
----------
chip_id : str
    ID of the chip
qid : str
    ID of the qubit
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
QubitResponse
    Qubit data
 * @summary Get a single qubit
 */
export const getChipQubit = (
  chipId: string,
  qid: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<QubitResponse>(
    { url: `/chips/${chipId}/qubits/${qid}`, method: "GET", signal },
    options,
  );
};

export const getGetChipQubitQueryKey = (chipId?: string, qid?: string) => {
  return [`/chips/${chipId}/qubits/${qid}`] as const;
};

export const getGetChipQubitQueryOptions = <
  TData = Awaited<ReturnType<typeof getChipQubit>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  qid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipQubit>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChipQubitQueryKey(chipId, qid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChipQubit>>> = ({
    signal,
  }) => getChipQubit(chipId, qid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && qid),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChipQubit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetChipQubitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChipQubit>>
>;
export type GetChipQubitQueryError = HTTPValidationError;

export function useGetChipQubit<
  TData = Awaited<ReturnType<typeof getChipQubit>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  qid: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipQubit>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipQubit>>,
          TError,
          Awaited<ReturnType<typeof getChipQubit>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetChipQubit<
  TData = Awaited<ReturnType<typeof getChipQubit>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  qid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipQubit>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipQubit>>,
          TError,
          Awaited<ReturnType<typeof getChipQubit>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChipQubit<
  TData = Awaited<ReturnType<typeof getChipQubit>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  qid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipQubit>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a single qubit
 */

export function useGetChipQubit<
  TData = Awaited<ReturnType<typeof getChipQubit>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  qid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChipQubit>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetChipQubitQueryOptions(chipId, qid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List couplings for a chip with pagination.

Retrieves coupling data from the separate CouplingDocument collection.

Parameters
----------
chip_id : str
    ID of the chip
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations
limit : int
    Maximum number of couplings to return (default 100, max 512)
offset : int
    Number of couplings to skip for pagination

Returns
-------
ListCouplingsResponse
    List of couplings with pagination info
 * @summary List couplings for a chip
 */
export const listChipCouplings = (
  chipId: string,
  params?: ListChipCouplingsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListCouplingsResponse>(
    { url: `/chips/${chipId}/couplings`, method: "GET", params, signal },
    options,
  );
};

export const getListChipCouplingsQueryKey = (
  chipId?: string,
  params?: ListChipCouplingsParams,
) => {
  return [`/chips/${chipId}/couplings`, ...(params ? [params] : [])] as const;
};

export const getListChipCouplingsQueryOptions = <
  TData = Awaited<ReturnType<typeof listChipCouplings>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipCouplingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listChipCouplings>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListChipCouplingsQueryKey(chipId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listChipCouplings>>
  > = ({ signal }) => listChipCouplings(chipId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listChipCouplings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListChipCouplingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listChipCouplings>>
>;
export type ListChipCouplingsQueryError = HTTPValidationError;

export function useListChipCouplings<
  TData = Awaited<ReturnType<typeof listChipCouplings>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params: undefined | ListChipCouplingsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listChipCouplings>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipCouplings>>,
          TError,
          Awaited<ReturnType<typeof listChipCouplings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListChipCouplings<
  TData = Awaited<ReturnType<typeof listChipCouplings>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipCouplingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listChipCouplings>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChipCouplings>>,
          TError,
          Awaited<ReturnType<typeof listChipCouplings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListChipCouplings<
  TData = Awaited<ReturnType<typeof listChipCouplings>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipCouplingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listChipCouplings>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List couplings for a chip
 */

export function useListChipCouplings<
  TData = Awaited<ReturnType<typeof listChipCouplings>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  params?: ListChipCouplingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listChipCouplings>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListChipCouplingsQueryOptions(
    chipId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a single coupling by ID.

Parameters
----------
chip_id : str
    ID of the chip
coupling_id : str
    ID of the coupling (e.g., "0-1")
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
CouplingResponse
    Coupling data
 * @summary Get a single coupling
 */
export const getChipCoupling = (
  chipId: string,
  couplingId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CouplingResponse>(
    { url: `/chips/${chipId}/couplings/${couplingId}`, method: "GET", signal },
    options,
  );
};

export const getGetChipCouplingQueryKey = (
  chipId?: string,
  couplingId?: string,
) => {
  return [`/chips/${chipId}/couplings/${couplingId}`] as const;
};

export const getGetChipCouplingQueryOptions = <
  TData = Awaited<ReturnType<typeof getChipCoupling>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  couplingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipCoupling>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChipCouplingQueryKey(chipId, couplingId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChipCoupling>>> = ({
    signal,
  }) => getChipCoupling(chipId, couplingId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && couplingId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChipCoupling>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetChipCouplingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChipCoupling>>
>;
export type GetChipCouplingQueryError = HTTPValidationError;

export function useGetChipCoupling<
  TData = Awaited<ReturnType<typeof getChipCoupling>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  couplingId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipCoupling>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipCoupling>>,
          TError,
          Awaited<ReturnType<typeof getChipCoupling>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetChipCoupling<
  TData = Awaited<ReturnType<typeof getChipCoupling>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  couplingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipCoupling>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipCoupling>>,
          TError,
          Awaited<ReturnType<typeof getChipCoupling>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChipCoupling<
  TData = Awaited<ReturnType<typeof getChipCoupling>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  couplingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipCoupling>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a single coupling
 */

export function useGetChipCoupling<
  TData = Awaited<ReturnType<typeof getChipCoupling>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  couplingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipCoupling>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetChipCouplingQueryOptions(
    chipId,
    couplingId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get aggregated metrics summary for a chip.

Computes statistics (averages, counts) on the database side.
Returns ~0.1KB of data, ideal for dashboard overview.

Parameters
----------
chip_id : str
    ID of the chip
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
MetricsSummaryResponse
    Aggregated metrics summary
 * @summary Get aggregated metrics summary
 */
export const getChipMetricsSummary = (
  chipId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MetricsSummaryResponse>(
    { url: `/chips/${chipId}/metrics/summary`, method: "GET", signal },
    options,
  );
};

export const getGetChipMetricsSummaryQueryKey = (chipId?: string) => {
  return [`/chips/${chipId}/metrics/summary`] as const;
};

export const getGetChipMetricsSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getChipMetricsSummary>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricsSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChipMetricsSummaryQueryKey(chipId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChipMetricsSummary>>
  > = ({ signal }) => getChipMetricsSummary(chipId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!chipId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChipMetricsSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetChipMetricsSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChipMetricsSummary>>
>;
export type GetChipMetricsSummaryQueryError = HTTPValidationError;

export function useGetChipMetricsSummary<
  TData = Awaited<ReturnType<typeof getChipMetricsSummary>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipMetricsSummary>>,
          TError,
          Awaited<ReturnType<typeof getChipMetricsSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetChipMetricsSummary<
  TData = Awaited<ReturnType<typeof getChipMetricsSummary>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipMetricsSummary>>,
          TError,
          Awaited<ReturnType<typeof getChipMetricsSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChipMetricsSummary<
  TData = Awaited<ReturnType<typeof getChipMetricsSummary>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricsSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get aggregated metrics summary
 */

export function useGetChipMetricsSummary<
  TData = Awaited<ReturnType<typeof getChipMetricsSummary>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricsSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetChipMetricsSummaryQueryOptions(chipId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get heatmap data for a single metric.

Returns only the values needed for heatmap visualization (~5KB).
Much more efficient than fetching full chip data (~300KB+).

Supported metrics:
- Qubit: t1, t2_echo, t2_star, qubit_frequency, anharmonicity,
         average_readout_fidelity, x90_gate_fidelity, x180_gate_fidelity
- Coupling: zx90_gate_fidelity, bell_state_fidelity, static_zz_interaction

Parameters
----------
chip_id : str
    ID of the chip
metric : str
    Name of the metric to retrieve
ctx : ProjectContext
    Project context with user and project information
chip_service : ChipService
    Service for chip operations

Returns
-------
MetricHeatmapResponse
    Metric values keyed by qubit/coupling ID
 * @summary Get heatmap data for a single metric
 */
export const getChipMetricHeatmap = (
  chipId: string,
  metric: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<MetricHeatmapResponse>(
    {
      url: `/chips/${chipId}/metrics/heatmap/${metric}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetChipMetricHeatmapQueryKey = (
  chipId?: string,
  metric?: string,
) => {
  return [`/chips/${chipId}/metrics/heatmap/${metric}`] as const;
};

export const getGetChipMetricHeatmapQueryOptions = <
  TData = Awaited<ReturnType<typeof getChipMetricHeatmap>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  metric: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricHeatmap>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChipMetricHeatmapQueryKey(chipId, metric);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChipMetricHeatmap>>
  > = ({ signal }) =>
    getChipMetricHeatmap(chipId, metric, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(chipId && metric),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChipMetricHeatmap>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetChipMetricHeatmapQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChipMetricHeatmap>>
>;
export type GetChipMetricHeatmapQueryError = HTTPValidationError;

export function useGetChipMetricHeatmap<
  TData = Awaited<ReturnType<typeof getChipMetricHeatmap>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  metric: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricHeatmap>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipMetricHeatmap>>,
          TError,
          Awaited<ReturnType<typeof getChipMetricHeatmap>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetChipMetricHeatmap<
  TData = Awaited<ReturnType<typeof getChipMetricHeatmap>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  metric: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricHeatmap>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChipMetricHeatmap>>,
          TError,
          Awaited<ReturnType<typeof getChipMetricHeatmap>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetChipMetricHeatmap<
  TData = Awaited<ReturnType<typeof getChipMetricHeatmap>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  metric: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricHeatmap>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get heatmap data for a single metric
 */

export function useGetChipMetricHeatmap<
  TData = Awaited<ReturnType<typeof getChipMetricHeatmap>>,
  TError = HTTPValidationError,
>(
  chipId: string,
  metric: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChipMetricHeatmap>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetChipMetricHeatmapQueryOptions(
    chipId,
    metric,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
