/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BackendConfigResponse,
  GetTaskFileContent200,
  GetTaskFileContentParams,
  GetTaskFileTreeParams,
  HTTPValidationError,
  ListTaskFileBackendsResponse,
  ListTaskInfoParams,
  ListTaskInfoResponse,
  SaveTaskFileContent200,
  SaveTaskFileRequest,
  TaskFileSettings,
  TaskFileTreeNode,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get task file settings from config/settings.yaml.

Returns
-------
    Task file settings including default backend
 * @summary Get task file settings
 */
export const getTaskFileSettings = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskFileSettings>(
    { url: `/task-files/settings`, method: "GET", signal },
    options,
  );
};

export const getGetTaskFileSettingsQueryKey = () => {
  return [`/task-files/settings`] as const;
};

export const getGetTaskFileSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskFileSettings>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getTaskFileSettings>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaskFileSettingsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTaskFileSettings>>
  > = ({ signal }) => getTaskFileSettings(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskFileSettings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTaskFileSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTaskFileSettings>>
>;
export type GetTaskFileSettingsQueryError = unknown;

export function useGetTaskFileSettings<
  TData = Awaited<ReturnType<typeof getTaskFileSettings>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileSettings>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskFileSettings>>,
          TError,
          Awaited<ReturnType<typeof getTaskFileSettings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTaskFileSettings<
  TData = Awaited<ReturnType<typeof getTaskFileSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileSettings>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskFileSettings>>,
          TError,
          Awaited<ReturnType<typeof getTaskFileSettings>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTaskFileSettings<
  TData = Awaited<ReturnType<typeof getTaskFileSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileSettings>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get task file settings
 */

export function useGetTaskFileSettings<
  TData = Awaited<ReturnType<typeof getTaskFileSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileSettings>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTaskFileSettingsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List all available backend directories in calibtasks.

Returns
-------
    List of backend names and paths
 * @summary List available task file backends
 */
export const listTaskFileBackends = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListTaskFileBackendsResponse>(
    { url: `/task-files/backends`, method: "GET", signal },
    options,
  );
};

export const getListTaskFileBackendsQueryKey = () => {
  return [`/task-files/backends`] as const;
};

export const getListTaskFileBackendsQueryOptions = <
  TData = Awaited<ReturnType<typeof listTaskFileBackends>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listTaskFileBackends>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTaskFileBackendsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listTaskFileBackends>>
  > = ({ signal }) => listTaskFileBackends(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTaskFileBackends>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListTaskFileBackendsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTaskFileBackends>>
>;
export type ListTaskFileBackendsQueryError = unknown;

export function useListTaskFileBackends<
  TData = Awaited<ReturnType<typeof listTaskFileBackends>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskFileBackends>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaskFileBackends>>,
          TError,
          Awaited<ReturnType<typeof listTaskFileBackends>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListTaskFileBackends<
  TData = Awaited<ReturnType<typeof listTaskFileBackends>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskFileBackends>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaskFileBackends>>,
          TError,
          Awaited<ReturnType<typeof listTaskFileBackends>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListTaskFileBackends<
  TData = Awaited<ReturnType<typeof listTaskFileBackends>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskFileBackends>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List available task file backends
 */

export function useListTaskFileBackends<
  TData = Awaited<ReturnType<typeof listTaskFileBackends>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listTaskFileBackends>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListTaskFileBackendsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get file tree structure for a specific backend directory.

Args:
----
    backend: Backend name (e.g., "qubex", "fake")

Returns:
-------
    File tree structure for the backend
 * @summary Get file tree for a specific backend
 */
export const getTaskFileTree = (
  params: GetTaskFileTreeParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<TaskFileTreeNode[]>(
    { url: `/task-files/tree`, method: "GET", params, signal },
    options,
  );
};

export const getGetTaskFileTreeQueryKey = (params?: GetTaskFileTreeParams) => {
  return [`/task-files/tree`, ...(params ? [params] : [])] as const;
};

export const getGetTaskFileTreeQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskFileTree>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileTreeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileTree>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaskFileTreeQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskFileTree>>> = ({
    signal,
  }) => getTaskFileTree(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskFileTree>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTaskFileTreeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTaskFileTree>>
>;
export type GetTaskFileTreeQueryError = HTTPValidationError;

export function useGetTaskFileTree<
  TData = Awaited<ReturnType<typeof getTaskFileTree>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileTreeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileTree>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskFileTree>>,
          TError,
          Awaited<ReturnType<typeof getTaskFileTree>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTaskFileTree<
  TData = Awaited<ReturnType<typeof getTaskFileTree>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileTreeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileTree>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskFileTree>>,
          TError,
          Awaited<ReturnType<typeof getTaskFileTree>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTaskFileTree<
  TData = Awaited<ReturnType<typeof getTaskFileTree>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileTreeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileTree>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get file tree for a specific backend
 */

export function useGetTaskFileTree<
  TData = Awaited<ReturnType<typeof getTaskFileTree>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileTreeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileTree>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTaskFileTreeQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get task file content for viewing/editing.

Args:
----
    path: Relative path from CALIBTASKS_BASE_PATH

Returns:
-------
    File content and metadata
 * @summary Get task file content for viewing/editing
 */
export const getTaskFileContent = (
  params: GetTaskFileContentParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTaskFileContent200>(
    { url: `/task-files/content`, method: "GET", params, signal },
    options,
  );
};

export const getGetTaskFileContentQueryKey = (
  params?: GetTaskFileContentParams,
) => {
  return [`/task-files/content`, ...(params ? [params] : [])] as const;
};

export const getGetTaskFileContentQueryOptions = <
  TData = Awaited<ReturnType<typeof getTaskFileContent>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileContent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTaskFileContentQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTaskFileContent>>
  > = ({ signal }) => getTaskFileContent(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTaskFileContent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTaskFileContentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTaskFileContent>>
>;
export type GetTaskFileContentQueryError = HTTPValidationError;

export function useGetTaskFileContent<
  TData = Awaited<ReturnType<typeof getTaskFileContent>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileContentParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileContent>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskFileContent>>,
          TError,
          Awaited<ReturnType<typeof getTaskFileContent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTaskFileContent<
  TData = Awaited<ReturnType<typeof getTaskFileContent>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileContent>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskFileContent>>,
          TError,
          Awaited<ReturnType<typeof getTaskFileContent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTaskFileContent<
  TData = Awaited<ReturnType<typeof getTaskFileContent>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileContent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get task file content for viewing/editing
 */

export function useGetTaskFileContent<
  TData = Awaited<ReturnType<typeof getTaskFileContent>>,
  TError = HTTPValidationError,
>(
  params: GetTaskFileContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTaskFileContent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTaskFileContentQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Save task file content.

Args:
----
    request: Save file request with path and content

Returns:
-------
    Success message
 * @summary Save task file content
 */
export const saveTaskFileContent = (
  saveTaskFileRequest: SaveTaskFileRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SaveTaskFileContent200>(
    {
      url: `/task-files/content`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: saveTaskFileRequest,
    },
    options,
  );
};

export const getSaveTaskFileContentMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveTaskFileContent>>,
    TError,
    { data: SaveTaskFileRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof saveTaskFileContent>>,
  TError,
  { data: SaveTaskFileRequest },
  TContext
> => {
  const mutationKey = ["saveTaskFileContent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof saveTaskFileContent>>,
    { data: SaveTaskFileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return saveTaskFileContent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SaveTaskFileContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof saveTaskFileContent>>
>;
export type SaveTaskFileContentMutationBody = SaveTaskFileRequest;
export type SaveTaskFileContentMutationError = HTTPValidationError;

/**
 * @summary Save task file content
 */
export const useSaveTaskFileContent = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof saveTaskFileContent>>,
      TError,
      { data: SaveTaskFileRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof saveTaskFileContent>>,
  TError,
  { data: SaveTaskFileRequest },
  TContext
> => {
  const mutationOptions = getSaveTaskFileContentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get backend configuration from backend.yaml.

Returns
-------
    Backend configuration
 * @summary Get backend configuration
 */
export const getBackendConfig = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<BackendConfigResponse>(
    { url: `/task-files/backend-config`, method: "GET", signal },
    options,
  );
};

export const getGetBackendConfigQueryKey = () => {
  return [`/task-files/backend-config`] as const;
};

export const getGetBackendConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getBackendConfig>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getBackendConfig>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBackendConfigQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBackendConfig>>
  > = ({ signal }) => getBackendConfig(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBackendConfig>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetBackendConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBackendConfig>>
>;
export type GetBackendConfigQueryError = unknown;

export function useGetBackendConfig<
  TData = Awaited<ReturnType<typeof getBackendConfig>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBackendConfig>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBackendConfig>>,
          TError,
          Awaited<ReturnType<typeof getBackendConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetBackendConfig<
  TData = Awaited<ReturnType<typeof getBackendConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBackendConfig>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBackendConfig>>,
          TError,
          Awaited<ReturnType<typeof getBackendConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetBackendConfig<
  TData = Awaited<ReturnType<typeof getBackendConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBackendConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get backend configuration
 */

export function useGetBackendConfig<
  TData = Awaited<ReturnType<typeof getBackendConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBackendConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetBackendConfigQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List all task definitions found in a backend directory.

Args:
----
    backend: Backend name (e.g., "qubex", "fake")
    sort_order: Sort order for tasks
    enabled_only: If True, only return tasks that are enabled

Returns:
-------
    List of task information
 * @summary List all tasks in a backend
 */
export const listTaskInfo = (
  params: ListTaskInfoParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListTaskInfoResponse>(
    { url: `/task-files/tasks`, method: "GET", params, signal },
    options,
  );
};

export const getListTaskInfoQueryKey = (params?: ListTaskInfoParams) => {
  return [`/task-files/tasks`, ...(params ? [params] : [])] as const;
};

export const getListTaskInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof listTaskInfo>>,
  TError = HTTPValidationError,
>(
  params: ListTaskInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTaskInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTaskInfoQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTaskInfo>>> = ({
    signal,
  }) => listTaskInfo(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTaskInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListTaskInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTaskInfo>>
>;
export type ListTaskInfoQueryError = HTTPValidationError;

export function useListTaskInfo<
  TData = Awaited<ReturnType<typeof listTaskInfo>>,
  TError = HTTPValidationError,
>(
  params: ListTaskInfoParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTaskInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaskInfo>>,
          TError,
          Awaited<ReturnType<typeof listTaskInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListTaskInfo<
  TData = Awaited<ReturnType<typeof listTaskInfo>>,
  TError = HTTPValidationError,
>(
  params: ListTaskInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTaskInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaskInfo>>,
          TError,
          Awaited<ReturnType<typeof listTaskInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListTaskInfo<
  TData = Awaited<ReturnType<typeof listTaskInfo>>,
  TError = HTTPValidationError,
>(
  params: ListTaskInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTaskInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List all tasks in a backend
 */

export function useListTaskInfo<
  TData = Awaited<ReturnType<typeof listTaskInfo>>,
  TError = HTTPValidationError,
>(
  params: ListTaskInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTaskInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListTaskInfoQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
