/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetTopologyById200,
  HTTPValidationError,
  ListTopologies200,
  ListTopologiesParams,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * List all available topology definitions.

Args:
----
    size: Optional filter by number of qubits

Returns:
-------
    dict: List of topology summaries with id, name, and num_qubits
 * @summary List available topologies
 */
export const listTopologies = (
  params?: ListTopologiesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListTopologies200>(
    { url: `/topology/list`, method: "GET", params, signal },
    options,
  );
};

export const getListTopologiesQueryKey = (params?: ListTopologiesParams) => {
  return [`/topology/list`, ...(params ? [params] : [])] as const;
};

export const getListTopologiesQueryOptions = <
  TData = Awaited<ReturnType<typeof listTopologies>>,
  TError = HTTPValidationError,
>(
  params?: ListTopologiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTopologies>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTopologiesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTopologies>>> = ({
    signal,
  }) => listTopologies(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTopologies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListTopologiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTopologies>>
>;
export type ListTopologiesQueryError = HTTPValidationError;

export function useListTopologies<
  TData = Awaited<ReturnType<typeof listTopologies>>,
  TError = HTTPValidationError,
>(
  params: undefined | ListTopologiesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTopologies>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTopologies>>,
          TError,
          Awaited<ReturnType<typeof listTopologies>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListTopologies<
  TData = Awaited<ReturnType<typeof listTopologies>>,
  TError = HTTPValidationError,
>(
  params?: ListTopologiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTopologies>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTopologies>>,
          TError,
          Awaited<ReturnType<typeof listTopologies>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListTopologies<
  TData = Awaited<ReturnType<typeof listTopologies>>,
  TError = HTTPValidationError,
>(
  params?: ListTopologiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTopologies>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List available topologies
 */

export function useListTopologies<
  TData = Awaited<ReturnType<typeof listTopologies>>,
  TError = HTTPValidationError,
>(
  params?: ListTopologiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTopologies>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListTopologiesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a specific topology definition.

Args:
----
    topology_id: Topology identifier (e.g., "square-lattice-mux-64")

Returns:
-------
    dict: Complete topology definition with qubits and couplings
 * @summary Get topology by ID
 */
export const getTopologyById = (
  topologyId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetTopologyById200>(
    { url: `/topology/${topologyId}`, method: "GET", signal },
    options,
  );
};

export const getGetTopologyByIdQueryKey = (topologyId?: string) => {
  return [`/topology/${topologyId}`] as const;
};

export const getGetTopologyByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTopologyById>>,
  TError = HTTPValidationError,
>(
  topologyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTopologyById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTopologyByIdQueryKey(topologyId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopologyById>>> = ({
    signal,
  }) => getTopologyById(topologyId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!topologyId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTopologyById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetTopologyByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTopologyById>>
>;
export type GetTopologyByIdQueryError = HTTPValidationError;

export function useGetTopologyById<
  TData = Awaited<ReturnType<typeof getTopologyById>>,
  TError = HTTPValidationError,
>(
  topologyId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTopologyById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopologyById>>,
          TError,
          Awaited<ReturnType<typeof getTopologyById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTopologyById<
  TData = Awaited<ReturnType<typeof getTopologyById>>,
  TError = HTTPValidationError,
>(
  topologyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTopologyById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopologyById>>,
          TError,
          Awaited<ReturnType<typeof getTopologyById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTopologyById<
  TData = Awaited<ReturnType<typeof getTopologyById>>,
  TError = HTTPValidationError,
>(
  topologyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTopologyById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get topology by ID
 */

export function useGetTopologyById<
  TData = Awaited<ReturnType<typeof getTopologyById>>,
  TError = HTTPValidationError,
>(
  topologyId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTopologyById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTopologyByIdQueryOptions(topologyId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
