/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AnalysisResponse,
  AnalyzeRequest,
  GetCopilotConfig200,
  HTTPValidationError,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get Copilot configuration for the metrics assistant.

Retrieves the Copilot configuration from YAML, including:
- enabled: Whether Copilot is enabled
- evaluation_metrics: Which metrics to use for multi-metric evaluation
- scoring: Thresholds for good/excellent ratings per metric
- system_prompt: The AI assistant's system prompt
- initial_message: The initial greeting message

Returns
-------
dict[str, Any]
    Copilot configuration dictionary
 * @summary Get Copilot configuration
 */
export const getCopilotConfig = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<GetCopilotConfig200>(
    { url: `/copilot/config`, method: "GET", signal },
    options,
  );
};

export const getGetCopilotConfigQueryKey = () => {
  return [`/copilot/config`] as const;
};

export const getGetCopilotConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getCopilotConfig>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCopilotConfig>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCopilotConfigQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCopilotConfig>>
  > = ({ signal }) => getCopilotConfig(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCopilotConfig>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetCopilotConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCopilotConfig>>
>;
export type GetCopilotConfigQueryError = unknown;

export function useGetCopilotConfig<
  TData = Awaited<ReturnType<typeof getCopilotConfig>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCopilotConfig>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCopilotConfig>>,
          TError,
          Awaited<ReturnType<typeof getCopilotConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetCopilotConfig<
  TData = Awaited<ReturnType<typeof getCopilotConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCopilotConfig>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCopilotConfig>>,
          TError,
          Awaited<ReturnType<typeof getCopilotConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetCopilotConfig<
  TData = Awaited<ReturnType<typeof getCopilotConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCopilotConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get Copilot configuration
 */

export function useGetCopilotConfig<
  TData = Awaited<ReturnType<typeof getCopilotConfig>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCopilotConfig>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetCopilotConfigQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Analyze a calibration task result using LLM.

Constructs a rich context from task knowledge, qubit parameters,
and experimental data, then sends it to the configured LLM for analysis.

Parameters
----------
request : AnalyzeRequest
    The analysis request containing task info, IDs, and user message.

Returns
-------
AnalysisResponse
    Structured analysis from the LLM.
 * @summary Analyze calibration result with AI
 */
export const analyzeCopilot = (
  analyzeRequest: AnalyzeRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AnalysisResponse>(
    {
      url: `/copilot/analyze`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: analyzeRequest,
      signal,
    },
    options,
  );
};

export const getAnalyzeCopilotMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof analyzeCopilot>>,
    TError,
    { data: AnalyzeRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof analyzeCopilot>>,
  TError,
  { data: AnalyzeRequest },
  TContext
> => {
  const mutationKey = ["analyzeCopilot"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof analyzeCopilot>>,
    { data: AnalyzeRequest }
  > = (props) => {
    const { data } = props ?? {};

    return analyzeCopilot(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AnalyzeCopilotMutationResult = NonNullable<
  Awaited<ReturnType<typeof analyzeCopilot>>
>;
export type AnalyzeCopilotMutationBody = AnalyzeRequest;
export type AnalyzeCopilotMutationError = HTTPValidationError;

/**
 * @summary Analyze calibration result with AI
 */
export const useAnalyzeCopilot = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof analyzeCopilot>>,
      TError,
      { data: AnalyzeRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof analyzeCopilot>>,
  TError,
  { data: AnalyzeRequest },
  TContext
> => {
  const mutationOptions = getAnalyzeCopilotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
