/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ActivityResponseStartedAt } from "./activityResponseStartedAt";
import type { ActivityResponseEndedAt } from "./activityResponseEndedAt";

/**
 * Response model for an activity (task execution).

Attributes
----------
activity_id : str
    Unique identifier (execution_id:task_id)
execution_id : str
    Parent execution ID
task_id : str
    Task identifier
task_name : str
    Name of the task
task_type : str
    Type of task
qid : str
    Qubit or coupling identifier
started_at : datetime | None
    When the activity started
ended_at : datetime | None
    When the activity ended
status : str
    Execution status
project_id : str
    Project identifier
chip_id : str
    Chip identifier
 */
export interface ActivityResponse {
  activity_id: string;
  execution_id: string;
  task_id: string;
  task_name: string;
  task_type?: string;
  qid?: string;
  started_at?: ActivityResponseStartedAt;
  ended_at?: ActivityResponseEndedAt;
  status?: string;
  project_id: string;
  chip_id?: string;
}
