/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Request to add a member to a project (always as viewer).
 */
export interface AddMemberRequest {
  username: string;
}
