/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UISettings } from "./uISettings";
import type { AllConfigResponseMetrics } from "./allConfigResponseMetrics";
import type { AllConfigResponseCopilot } from "./allConfigResponseCopilot";

/**
 * Response containing all application configuration.
 */
export interface AllConfigResponse {
  ui?: UISettings;
  metrics?: AllConfigResponseMetrics;
  copilot?: AllConfigResponseCopilot;
}
