/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Structured analysis returned by the LLM.
 */
export interface AnalysisResponse {
  /** One-line result summary */
  summary: string;
  /** Overall assessment: good / warning / bad */
  assessment: string;
  /** Detailed analysis and interpretation */
  explanation: string;
  /** Detected potential issues */
  potential_issues?: string[];
  /** Recommended next actions */
  recommendations?: string[];
}
