/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { AnalyzeRequestImageBase64 } from "./analyzeRequestImageBase64";
import type { AnalyzeRequestConversationHistoryItem } from "./analyzeRequestConversationHistoryItem";

/**
 * Request body for POST /copilot/analyze.
 */
export interface AnalyzeRequest {
  /** Task class name (e.g. CheckT1) */
  task_name: string;
  chip_id: string;
  qid: string;
  execution_id: string;
  task_id: string;
  /** User question / message */
  message: string;
  /** Base64-encoded result figure (for multimodal analysis) */
  image_base64?: AnalyzeRequestImageBase64;
  /** Previous conversation messages [{role, content}, ...] */
  conversation_history?: AnalyzeRequestConversationHistoryItem[];
}
