/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for backend operations.

Inherits from BackendModel and is used to format the response
for backend-related API endpoints.
 */
export interface BackendResponseModel {
  name: string;
  username: string;
}
