/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { BackendConfigResponseBackends } from "./backendConfigResponseBackends";
import type { BackendConfigResponseCategories } from "./backendConfigResponseCategories";

/**
 * Response model for backend configuration.
 */
export interface BackendConfigResponse {
  default_backend?: string;
  backends?: BackendConfigResponseBackends;
  categories?: BackendConfigResponseCategories;
}
