/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { BackendDefinitionResponse } from "./backendDefinitionResponse";

export type BackendConfigResponseBackends = {
  [key: string]: BackendDefinitionResponse;
};
