/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export interface BodyDownloadFiguresAsZip {
  /** List of file paths to include in the ZIP */
  paths: string[];
  /** Filename for the ZIP archive */
  filename?: string;
}
