/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { CalibrationNoteResponseNote } from "./calibrationNoteResponseNote";
import type { CalibrationNoteResponseTimestamp } from "./calibrationNoteResponseTimestamp";

/**
 * CalibrationNote is a subclass of BaseModel.
 */
export interface CalibrationNoteResponse {
  username: string;
  execution_id: string;
  task_id: string;
  note: CalibrationNoteResponseNote;
  timestamp?: CalibrationNoteResponseTimestamp;
}
