/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for cancelling an execution.
 */
export interface CancelExecutionResponse {
  execution_id: string;
  status: string;
  message: string;
}
