/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ChipMetricsResponseWithinHours } from "./chipMetricsResponseWithinHours";
import type { ChipMetricsResponseQubitMetrics } from "./chipMetricsResponseQubitMetrics";
import type { ChipMetricsResponseCouplingMetrics } from "./chipMetricsResponseCouplingMetrics";

/**
 * Complete chip metrics response.
 */
export interface ChipMetricsResponse {
  chip_id: string;
  username: string;
  qubit_count: number;
  within_hours?: ChipMetricsResponseWithinHours;
  qubit_metrics: ChipMetricsResponseQubitMetrics;
  coupling_metrics: ChipMetricsResponseCouplingMetrics;
}
