/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ChipResponseTopologyId } from "./chipResponseTopologyId";
import type { ChipResponseInstalledAt } from "./chipResponseInstalledAt";

/**
 * Chip response model.

Qubit and coupling data are stored in separate collections for scalability
and should be fetched via dedicated endpoints (/chips/{chip_id}/qubits, etc.).

Attributes
----------
    chip_id (str): The ID of the chip.
    size (int): The size of the chip.
    topology_id (str | None): Topology template ID.
    qubit_count (int): Number of qubits in the chip.
    coupling_count (int): Number of couplings in the chip.
    installed_at (datetime | None): Installation timestamp.
 */
export interface ChipResponse {
  chip_id: string;
  size?: number;
  topology_id?: ChipResponseTopologyId;
  qubit_count?: number;
  coupling_count?: number;
  installed_at?: ChipResponseInstalledAt;
}
