/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type CompareExecutionsParams = {
  /**
   * First execution ID (before)
   */
  execution_id_before: string;
  /**
   * Second execution ID (after)
   */
  execution_id_after: string;
};
