/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { FidelityCondition } from "./fidelityCondition";

/**
 * Condition for filtering device topology.
 */
export interface Condition {
  coupling_fidelity: FidelityCondition;
  qubit_fidelity: FidelityCondition;
  readout_fidelity: FidelityCondition;
  only_maximum_connected?: boolean;
}
