/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Gate duration of the coupling.
 */
export interface CouplingGateDuration {
  rzx90: number;
}
