/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { CouplingGateDuration } from "./couplingGateDuration";

/**
 * Coupling information.
 */
export interface Coupling {
  control: number;
  target: number;
  fidelity: number;
  gate_duration: CouplingGateDuration;
}
