/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { DegradationTrendResponseCurrentValue } from "./degradationTrendResponseCurrentValue";
import type { DegradationTrendResponseValidFrom } from "./degradationTrendResponseValidFrom";

/**
 * Response model for a single degradation trend (consecutive worsening).
 */
export interface DegradationTrendResponse {
  parameter_name: string;
  qid?: string;
  /** maximize or minimize */
  evaluation_mode: string;
  /** Consecutive worsening count */
  streak_count: number;
  /** Cumulative change over streak */
  total_delta: number;
  /** Cumulative change in % */
  total_delta_percent: number;
  /** Average delta per step */
  delta_per_step?: number;
  current_value?: DegradationTrendResponseCurrentValue;
  current_entity_id?: string;
  unit?: string;
  /** Recent values (oldest first) for sparkline */
  values?: number[];
  valid_from?: DegradationTrendResponseValidFrom;
}
