/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response for deleting a schedule.
 */
export interface DeleteScheduleResponse {
  /** Success message */
  message: string;
  /** Deleted schedule ID */
  schedule_id: string;
  /** Type of deleted schedule (cron or one-time) */
  schedule_type: string;
}
