/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { Condition } from "./condition";

/**
 * Request model for device topology.
 */
export interface DeviceTopologyRequest {
  name?: string;
  device_id?: string;
  qubits?: string[];
  exclude_couplings?: string[];
  condition?: Condition;
}
