/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { DownloadMetricsPdfSelectionMode } from "./downloadMetricsPdfSelectionMode";

export type DownloadMetricsPdfParams = {
  /**
   * Filter to data within N hours
   */
  within_hours?: number | null;
  /**
   * Selection mode: 'latest', 'best', or 'average'
   */
  selection_mode?: DownloadMetricsPdfSelectionMode;
};
