/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type DownloadMetricsPdfSelectionMode =
  (typeof DownloadMetricsPdfSelectionMode)[keyof typeof DownloadMetricsPdfSelectionMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DownloadMetricsPdfSelectionMode = {
  latest: "latest",
  best: "best",
  average: "average",
} as const;
