/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecuteFlowRequestParameters } from "./executeFlowRequestParameters";

/**
 * Request to execute a Flow.
 */
export interface ExecuteFlowRequest {
  /** Execution parameters (overrides default_parameters) */
  parameters?: ExecuteFlowRequestParameters;
}
