/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response after executing a flow.
 */
export interface ExecuteFlowResponse {
  /** Execution ID */
  execution_id: string;
  /** Prefect flow run URL */
  flow_run_url: string;
  /** QDash UI URL for execution */
  qdash_ui_url: string;
  /** Success message */
  message: string;
}
