/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutionIdResponseValidFrom } from "./executionIdResponseValidFrom";

/**
 * Response model for a single execution ID with timestamp.

Attributes
----------
execution_id : str
    The unique execution identifier
valid_from : datetime | None
    When parameters from this execution were created
 */
export interface ExecutionIdResponse {
  /** Unique execution identifier */
  execution_id: string;
  /** Latest parameter timestamp */
  valid_from?: ExecutionIdResponseValidFrom;
}
