/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutionResponseDetailStartAt } from "./executionResponseDetailStartAt";
import type { ExecutionResponseDetailEndAt } from "./executionResponseDetailEndAt";
import type { ExecutionResponseDetailElapsedTime } from "./executionResponseDetailElapsedTime";
import type { Task } from "./task";
import type { ExecutionResponseDetailNote } from "./executionResponseDetailNote";

/**
 * ExecutionResponseDetail is a Pydantic model that represents the detail of an execution response.

Attributes
----------
    name (str): The name of the execution.
    status (str): The current status of the execution.
    start_at (datetime | None): The start time of the execution.
    end_at (datetime | None): The end time of the execution.
    elapsed_time (timedelta | None): The total elapsed time of the execution.
    task (list[Task]): List of tasks in the execution.
    note (dict): Notes for the execution.
    tags (list[str]): Tags associated with the execution.
    chip_id (str): The chip ID for the execution.
 */
export interface ExecutionResponseDetail {
  name: string;
  status: string;
  flow_name?: string;
  start_at?: ExecutionResponseDetailStartAt;
  end_at?: ExecutionResponseDetailEndAt;
  elapsed_time?: ExecutionResponseDetailElapsedTime;
  task: Task[];
  note: ExecutionResponseDetailNote;
  tags?: string[];
  chip_id?: string;
}
