/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutionResponseSummaryStartAt } from "./executionResponseSummaryStartAt";
import type { ExecutionResponseSummaryEndAt } from "./executionResponseSummaryEndAt";
import type { ExecutionResponseSummaryElapsedTime } from "./executionResponseSummaryElapsedTime";
import type { ExecutionResponseSummaryNote } from "./executionResponseSummaryNote";

/**
 * ExecutionResponseSummary is a Pydantic model that represents the summary of an execution response.

Attributes
----------
    name (str): The name of the execution.
    execution_id (str): The ID of the execution.
    status (str): The current status of the execution.
    start_at (datetime | None): The start time of the execution.
    end_at (datetime | None): The end time of the execution.
    elapsed_time (timedelta | None): The total elapsed time of the execution.
    tags (list[str]): Tags associated with the execution.
    note (dict): Notes for the execution.
 */
export interface ExecutionResponseSummary {
  name: string;
  execution_id: string;
  status: string;
  start_at?: ExecutionResponseSummaryStartAt;
  end_at?: ExecutionResponseSummaryEndAt;
  elapsed_time?: ExecutionResponseSummaryElapsedTime;
  tags: string[];
  note: ExecutionResponseSummaryNote;
}
