/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for the fetch_execution_lock_status endpoint.
 */
export interface ExecutionLockStatusResponse {
  lock: boolean;
}
