/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ParameterDiffResponse } from "./parameterDiffResponse";

/**
 * Response model for execution comparison.

Attributes
----------
execution_id_before : str
    First execution ID
execution_id_after : str
    Second execution ID
added_parameters : list[ParameterDiffResponse]
    Parameters added in the second execution
removed_parameters : list[ParameterDiffResponse]
    Parameters removed in the second execution
changed_parameters : list[ParameterDiffResponse]
    Parameters with different values
unchanged_count : int
    Count of unchanged parameters
 */
export interface ExecutionComparisonResponse {
  execution_id_before: string;
  execution_id_after: string;
  added_parameters: ParameterDiffResponse[];
  removed_parameters: ParameterDiffResponse[];
  changed_parameters: ParameterDiffResponse[];
  unchanged_count: number;
}
