/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for expected result description.
 */
export interface ExpectedResultResponse {
  description: string;
  result_type?: string;
  x_axis?: string;
  y_axis?: string;
  z_axis?: string;
  fit_model?: string;
  typical_range?: string;
  good_visual?: string;
}
