/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for a structured failure mode.
 */
export interface FailureModeResponse {
  severity: string;
  description: string;
  cause?: string;
  visual?: string;
  next_action?: string;
}
