/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Condition for fidelity filtering.
 */
export interface FidelityCondition {
  min: number;
  max: number;
  is_within_24h?: boolean;
}
