/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * File node type enum.
 */
export type FileNodeType = (typeof FileNodeType)[keyof typeof FileNodeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileNodeType = {
  file: "file",
  directory: "directory",
} as const;
