/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { FileTreeNodeChildren } from "./fileTreeNodeChildren";

/**
 * File tree node model.
 */
export interface FileTreeNode {
  name: string;
  path: string;
  type: string;
  children?: FileTreeNodeChildren;
}
