/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Summary of a Flow for listing.
 */
export interface FlowSummary {
  /** Flow name */
  name: string;
  /** Flow description */
  description: string;
  /** Target chip ID */
  chip_id: string;
  /** Entry point function name */
  flow_function_name: string;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at: string;
  /** Tags */
  tags: string[];
}
