/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { FlowScheduleSummaryCron } from "./flowScheduleSummaryCron";
import type { FlowScheduleSummaryNextRun } from "./flowScheduleSummaryNextRun";

/**
 * Summary of a scheduled Flow.
 */
export interface FlowScheduleSummary {
  /** Schedule ID */
  schedule_id: string;
  /** Flow name */
  flow_name: string;
  /** Schedule type: 'cron' or 'one-time' */
  schedule_type: string;
  /** Cron expression */
  cron?: FlowScheduleSummaryCron;
  /** Next scheduled run time */
  next_run?: FlowScheduleSummaryNextRun;
  /** Whether the schedule is active */
  active: boolean;
  /** Schedule creation time */
  created_at: string;
}
