/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetCouplingMetricHistoryParams = {
  /**
   * Metric name (e.g., zx90_gate_fidelity, bell_state_fidelity)
   */
  metric: string;
  /**
   * Max number of history items (None for unlimited)
   */
  limit?: number | null;
  /**
   * Filter to last N days
   */
  within_days?: number | null;
};
