/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetChipMetricsSelectionMode =
  (typeof GetChipMetricsSelectionMode)[keyof typeof GetChipMetricsSelectionMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetChipMetricsSelectionMode = {
  latest: "latest",
  best: "best",
  average: "average",
} as const;
