/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { GetFlowResponseDefaultParameters } from "./getFlowResponseDefaultParameters";
import type { GetFlowResponseDefaultRunParameters } from "./getFlowResponseDefaultRunParameters";

/**
 * Response for getting flow details.
 */
export interface GetFlowResponse {
  /** Flow name */
  name: string;
  /** Flow description */
  description: string;
  /** Python code content */
  code: string;
  /** Entry point function name */
  flow_function_name: string;
  /** Target chip ID */
  chip_id: string;
  /** Default parameters */
  default_parameters: GetFlowResponseDefaultParameters;
  /** Default run parameters applied to all tasks */
  default_run_parameters?: GetFlowResponseDefaultRunParameters;
  /** Path to file */
  file_path: string;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at: string;
  /** Tags */
  tags: string[];
}
