/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetProvenancePolicyViolationsParams = {
  /**
   * Filter by severity (warn)
   */
  severity?: string | null;
  /**
   * Maximum number of violations to return
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
  /**
   * Filter by parameter names
   */
  parameter_names?: string[] | null;
};
