/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetParameterHistoryParams = {
  /**
   * Name of the parameter
   */
  parameter_name: string;
  /**
   * Qubit or coupling identifier
   */
  qid: string;
  /**
   * Maximum number of versions
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
