/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetProvenanceImpactParams = {
  /**
   * Maximum traversal depth
   * @minimum 1
   * @maximum 20
   */
  max_depth?: number;
};
