/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetRecentChangesParams = {
  /**
   * Maximum number of changes to return
   * @minimum 1
   * @maximum 50
   */
  limit?: number;
  /**
   * Time window in hours
   * @minimum 1
   * @maximum 168
   */
  within_hours?: number;
  /**
   * Filter by parameter names (from metrics config)
   */
  parameter_names?: string[] | null;
};
