/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetRecentExecutionsParams = {
  /**
   * Maximum number of execution IDs to return
   * @minimum 1
   * @maximum 50
   */
  limit?: number;
};
