/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type GetTimeseriesTaskResultsParams = {
  /**
   * Chip ID
   */
  chip_id: string;
  /**
   * Tag to filter by
   */
  tag: string;
  /**
   * Parameter name
   */
  parameter: string;
  /**
   * Start time in ISO format
   */
  start_at: string;
  /**
   * End time in ISO format
   */
  end_at: string;
  /**
   * Optional qubit ID to filter by
   */
  qid?: string | null;
};
