/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Request model for Git push operation.
 */
export interface GitPushRequest {
  commit_message?: string;
}
