/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { LineageNodeResponse } from "./lineageNodeResponse";
import type { LineageEdgeResponse } from "./lineageEdgeResponse";

/**
 * Response model for impact query.

Attributes
----------
origin : LineageNodeResponse
    The queried entity
nodes : list[LineageNodeResponse]
    All nodes affected by this entity
edges : list[LineageEdgeResponse]
    All edges in the impact graph
max_depth : int
    Maximum depth traversed
 */
export interface ImpactResponse {
  origin: LineageNodeResponse;
  nodes: LineageNodeResponse[];
  edges: LineageEdgeResponse[];
  max_depth: number;
}
