/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { InputParameterModelValue } from "./inputParameterModelValue";

/**
 * Input parameter class.
 */
export interface InputParameterModel {
  unit?: string;
  value_type?: string;
  value?: InputParameterModelValue;
  description?: string;
}
