/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Parent issue ID for replies. None for root issues.
 */
export type IssueCreateParentId = string | null;
