/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Issue title. Required for root issues, None for replies.
 */
export type IssueCreateTitle = string | null;
