/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { IssueResponseTitle } from "./issueResponseTitle";
import type { IssueResponseParentId } from "./issueResponseParentId";

/**
 * Response schema for a single issue.
 */
export interface IssueResponse {
  /** Issue document ID */
  id: string;
  /** Associated task ID */
  task_id: string;
  /** Issue author username */
  username: string;
  /** Issue title */
  title?: IssueResponseTitle;
  /** Issue text content */
  content: string;
  /** When the issue was created */
  created_at: string;
  /** When the issue was last updated */
  updated_at: string;
  /** Parent issue ID for replies */
  parent_id?: IssueResponseParentId;
  /** Number of replies to this issue */
  reply_count?: number;
  /** Whether this thread is closed */
  is_closed?: boolean;
  /** Whether this reply was generated by AI */
  is_ai_reply?: boolean;
}
