/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { IssueKnowledgeUpdateTitle } from "./issueKnowledgeUpdateTitle";
import type { IssueKnowledgeUpdateSeverity } from "./issueKnowledgeUpdateSeverity";
import type { IssueKnowledgeUpdateSymptom } from "./issueKnowledgeUpdateSymptom";
import type { IssueKnowledgeUpdateRootCause } from "./issueKnowledgeUpdateRootCause";
import type { IssueKnowledgeUpdateResolution } from "./issueKnowledgeUpdateResolution";
import type { IssueKnowledgeUpdateLessonLearned } from "./issueKnowledgeUpdateLessonLearned";

/**
 * Request schema for editing a knowledge draft.
 */
export interface IssueKnowledgeUpdate {
  /** Updated title */
  title?: IssueKnowledgeUpdateTitle;
  /** Updated severity */
  severity?: IssueKnowledgeUpdateSeverity;
  /** Updated symptom */
  symptom?: IssueKnowledgeUpdateSymptom;
  /** Updated root cause */
  root_cause?: IssueKnowledgeUpdateRootCause;
  /** Updated resolution */
  resolution?: IssueKnowledgeUpdateResolution;
  /** Updated lessons */
  lesson_learned?: IssueKnowledgeUpdateLessonLearned;
}
