/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { IssueKnowledgeResponseReviewedBy } from "./issueKnowledgeResponseReviewedBy";
import type { IssueKnowledgeResponsePrUrl } from "./issueKnowledgeResponsePrUrl";

/**
 * Response schema for a knowledge case.
 */
export interface IssueKnowledgeResponse {
  /** Document ID */
  id: string;
  /** Source issue ID */
  issue_id: string;
  /** Associated task result ID */
  task_id: string;
  /** Calibration task class name */
  task_name: string;
  /** Lifecycle status: draft, approved, rejected */
  status: string;
  /** Short descriptive title */
  title: string;
  /** Date of the incident */
  date?: string;
  /** Severity level */
  severity?: string;
  /** Chip identifier */
  chip_id?: string;
  /** Qubit identifier */
  qid?: string;
  /** Case outcome */
  resolution_status?: string;
  /** Observed symptom */
  symptom?: string;
  /** Identified root cause */
  root_cause?: string;
  /** How the issue was resolved */
  resolution?: string;
  /** Key takeaways */
  lesson_learned?: string[];
  /** Task result figure paths */
  figure_paths?: string[];
  /** Image URLs from issue thread */
  thread_image_urls?: string[];
  /** Reviewer username */
  reviewed_by?: IssueKnowledgeResponseReviewedBy;
  /** GitHub PR URL (set on approve) */
  pr_url?: IssueKnowledgeResponsePrUrl;
  /** When the draft was created */
  created_at: string;
  /** When the draft was last updated */
  updated_at: string;
}
