/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { IssueCreateTitle } from "./issueCreateTitle";
import type { IssueCreateParentId } from "./issueCreateParentId";

/**
 * Request schema for creating an issue.
 */
export interface IssueCreate {
  /** Issue title. Required for root issues, None for replies. */
  title?: IssueCreateTitle;
  /**
   * Issue text content
   * @minLength 1
   * @maxLength 5000
   */
  content: string;
  /** Parent issue ID for replies. None for root issues. */
  parent_id?: IssueCreateParentId;
}
