/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for a task knowledge image reference.
 */
export interface KnowledgeImageResponse {
  alt_text: string;
  relative_path: string;
  section: string;
  base64_data?: string;
}
