/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for a knowledge case (postmortem).
 */
export interface KnowledgeCaseResponse {
  title: string;
  date?: string;
  severity?: string;
  chip_id?: string;
  qid?: string;
  status?: string;
  symptom?: string;
  root_cause?: string;
  resolution?: string;
  lesson_learned?: string[];
}
