/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { LatestTaskResultResponseResult } from "./latestTaskResultResponseResult";

/**
 * Response model for fetching the latest tasks grouped by qid/coupling_id.
 */
export interface LatestTaskResultResponse {
  task_name: string;
  result: LatestTaskResultResponseResult;
}
