/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { LineageNodeResponse } from "./lineageNodeResponse";
import type { LineageEdgeResponse } from "./lineageEdgeResponse";

/**
 * Response model for lineage query.

Attributes
----------
origin : LineageNodeResponse
    The queried entity
nodes : list[LineageNodeResponse]
    All nodes in the lineage graph
edges : list[LineageEdgeResponse]
    All edges in the lineage graph
max_depth : int
    Maximum depth traversed
 */
export interface LineageResponse {
  origin: LineageNodeResponse;
  nodes: LineageNodeResponse[];
  edges: LineageEdgeResponse[];
  max_depth: number;
}
