/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for an edge in the lineage graph.

Attributes
----------
relation_type : str
    Type of relation
source_id : str
    Source node identifier
target_id : str
    Target node identifier
 */
export interface LineageEdgeResponse {
  relation_type: string;
  source_id: string;
  target_id: string;
}
