/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { LineageNodeResponseEntity } from "./lineageNodeResponseEntity";
import type { LineageNodeResponseActivity } from "./lineageNodeResponseActivity";
import type { LineageNodeResponseLatestVersion } from "./lineageNodeResponseLatestVersion";

/**
 * Response model for a node in the lineage graph.

Attributes
----------
node_type : str
    Type of node (entity or activity)
node_id : str
    Identifier of the node
depth : int
    Distance from the queried entity (0 = origin)
entity : ParameterVersionResponse | None
    Entity details if node is an entity
activity : ActivityResponse | None
    Activity details if node is an activity
latest_version : int | None
    Current version of the parameter if newer than the node's version
 */
export interface LineageNodeResponse {
  node_type: string;
  node_id: string;
  depth?: number;
  entity?: LineageNodeResponseEntity;
  activity?: LineageNodeResponseActivity;
  latest_version?: LineageNodeResponseLatestVersion;
}
