/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type ListExecutionsParams = {
  /**
   * Chip ID to filter executions
   */
  chip_id: string;
  /**
   * Number of items to skip
   * @minimum 0
   */
  skip?: number;
  /**
   * Number of items to return
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
