/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { CouplingResponse } from "./couplingResponse";

/**
 * Response model for listing couplings with pagination.
 */
export interface ListCouplingsResponse {
  couplings: CouplingResponse[];
  total: number;
  limit: number;
  offset: number;
}
