/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type ListTaskInfoParams = {
  backend: string;
  sort_order?: string | null;
  enabled_only?: boolean;
};
