/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutionResponseSummary } from "./executionResponseSummary";
import type { ListExecutionsResponseTotal } from "./listExecutionsResponseTotal";
import type { ListExecutionsResponseSkip } from "./listExecutionsResponseSkip";
import type { ListExecutionsResponseLimit } from "./listExecutionsResponseLimit";

/**
 * Response model for listing executions.

Wraps list of executions for API consistency and future extensibility (e.g., pagination).
 */
export interface ListExecutionsResponse {
  executions: ExecutionResponseSummary[];
  total?: ListExecutionsResponseTotal;
  skip?: ListExecutionsResponseSkip;
  limit?: ListExecutionsResponseLimit;
}
