/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type ListIssueKnowledgeParams = {
  /**
   * @minimum 0
   */
  skip?: number;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
  /**
   * Filter by status: draft, approved, rejected
   */
  status?: string | null;
  /**
   * Filter by task name
   */
  task_name?: string | null;
};
