/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskInfo } from "./taskInfo";

/**
 * Response model for listing task info.
 */
export interface ListTaskInfoResponse {
  tasks: TaskInfo[];
}
