/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type ListIssuesParams = {
  /**
   * Number of items to skip
   * @minimum 0
   */
  skip?: number;
  /**
   * Max items to return
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
  /**
   * Filter by task ID
   */
  task_id?: string | null;
  /**
   * Filter by closed status. Default false (open only). Set to true for closed, or omit/null for all.
   */
  is_closed?: boolean | null;
};
