/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { QubitResponse } from "./qubitResponse";

/**
 * Response model for listing qubits with pagination.
 */
export interface ListQubitsResponse {
  qubits: QubitResponse[];
  total: number;
  limit: number;
  offset: number;
}
