/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

export type ListChipCouplingsParams = {
  /**
   * @minimum 1
   * @maximum 512
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};
