/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskResponse } from "./taskResponse";

/**
 * Response model for a list of tasks.
 */
export interface ListTaskResponse {
  tasks: TaskResponse[];
}
