/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ListMuxResponseMuxes } from "./listMuxResponseMuxes";

/**
 * ListMuxResponse is a Pydantic model that represents the response for fetching the multiplexers.
 */
export interface ListMuxResponse {
  muxes: ListMuxResponseMuxes;
}
