/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { IssueResponse } from "./issueResponse";

/**
 * Paginated list of issues.
 */
export interface ListIssuesResponse {
  issues: IssueResponse[];
  total: number;
  skip: number;
  limit: number;
}
