/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { Tag } from "./tag";

/**
 * Response model for a list of tags.
 */
export interface ListTagResponse {
  tags: Tag[];
}
