/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { IssueKnowledgeResponse } from "./issueKnowledgeResponse";

/**
 * Paginated list of knowledge cases.
 */
export interface ListIssueKnowledgeResponse {
  items: IssueKnowledgeResponse[];
  total: number;
  skip: number;
  limit: number;
}
