/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Measurement error of the qubit.
 */
export interface MeasError {
  prob_meas1_prep0: number;
  prob_meas0_prep1: number;
  readout_assignment_error: number;
}
