/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectRole } from "./projectRole";
import type { MemberResponseInvitedBy } from "./memberResponseInvitedBy";
import type { MemberResponseLastAccessedAt } from "./memberResponseLastAccessedAt";

/**
 * Response schema for project membership.
 */
export interface MemberResponse {
  project_id: string;
  username: string;
  role: ProjectRole;
  status: string;
  invited_by: MemberResponseInvitedBy;
  last_accessed_at: MemberResponseLastAccessedAt;
}
