/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MemberItemFullName } from "./memberItemFullName";
import type { ProjectRole } from "./projectRole";

/**
 * Member info for admin view.
 */
export interface MemberItem {
  username: string;
  full_name?: MemberItemFullName;
  role: ProjectRole;
  status?: string;
}
