/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MetricsSummaryResponseAverages } from "./metricsSummaryResponseAverages";

/**
 * Response model for aggregated metrics summary.

Returns statistical summary computed by the database.
Minimal data transfer (~0.1KB).
Metrics are loaded dynamically from metrics.yaml config.
 */
export interface MetricsSummaryResponse {
  chip_id: string;
  qubit_count: number;
  averages?: MetricsSummaryResponseAverages;
}
