/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MetricHeatmapResponseValues } from "./metricHeatmapResponseValues";
import type { MetricHeatmapResponseUnit } from "./metricHeatmapResponseUnit";

/**
 * Response model for metric heatmap data.

Returns only the metric values keyed by qubit/coupling ID.
Much smaller than full chip data (~5KB vs ~300KB for 64 qubits).
 */
export interface MetricHeatmapResponse {
  chip_id: string;
  metric: string;
  values: MetricHeatmapResponseValues;
  unit?: MetricHeatmapResponseUnit;
}
