/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MetricValueValue } from "./metricValueValue";
import type { MetricValueTaskId } from "./metricValueTaskId";
import type { MetricValueExecutionId } from "./metricValueExecutionId";
import type { MetricValueStddev } from "./metricValueStddev";

/**
 * Single metric value with metadata.
 */
export interface MetricValue {
  value?: MetricValueValue;
  task_id?: MetricValueTaskId;
  execution_id?: MetricValueExecutionId;
  stddev?: MetricValueStddev;
}
