/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ParameterVersionResponseValue } from "./parameterVersionResponseValue";
import type { ParameterVersionResponseValidFrom } from "./parameterVersionResponseValidFrom";
import type { ParameterVersionResponseValidUntil } from "./parameterVersionResponseValidUntil";

/**
 * Response model for a parameter version (entity).

Attributes
----------
entity_id : str
    Unique identifier for this parameter version
parameter_name : str
    Name of the parameter
qid : str
    Qubit or coupling identifier
value : float | int | str
    The parameter value
value_type : str
    Type of the value
unit : str
    Physical unit
error : float
    Measurement error/uncertainty
version : int
    Version number
valid_from : datetime
    When this version became valid
valid_until : datetime | None
    When this version was superseded
execution_id : str
    Execution that produced this value
task_id : str
    Task that produced this value
task_name : str
    Name of the task
project_id : str
    Project identifier
chip_id : str
    Chip identifier
 */
export interface ParameterVersionResponse {
  entity_id: string;
  parameter_name: string;
  qid?: string;
  value: ParameterVersionResponseValue;
  value_type?: string;
  unit?: string;
  error?: number;
  version: number;
  valid_from?: ParameterVersionResponseValidFrom;
  valid_until?: ParameterVersionResponseValidUntil;
  execution_id: string;
  task_id: string;
  task_name?: string;
  project_id: string;
  chip_id?: string;
}
