/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ParameterDiffResponseValueBefore } from "./parameterDiffResponseValueBefore";
import type { ParameterDiffResponseValueAfter } from "./parameterDiffResponseValueAfter";
import type { ParameterDiffResponseDelta } from "./parameterDiffResponseDelta";
import type { ParameterDiffResponseDeltaPercent } from "./parameterDiffResponseDeltaPercent";

/**
 * Response model for parameter difference between executions.

Attributes
----------
parameter_name : str
    Name of the parameter
qid : str
    Qubit or coupling identifier
value_before : float | int | str | None
    Value in the first execution
value_after : float | int | str | None
    Value in the second execution
delta : float | None
    Numeric difference if applicable
delta_percent : float | None
    Percentage change if applicable
 */
export interface ParameterDiffResponse {
  parameter_name: string;
  qid: string;
  value_before?: ParameterDiffResponseValueBefore;
  value_after?: ParameterDiffResponseValueAfter;
  delta?: ParameterDiffResponseDelta;
  delta_percent?: ParameterDiffResponseDeltaPercent;
}
