/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ParameterVersionResponse } from "./parameterVersionResponse";

/**
 * Response model for parameter version history.

Attributes
----------
parameter_name : str
    Name of the parameter
qid : str
    Qubit or coupling identifier
versions : list[ParameterVersionResponse]
    List of all versions, newest first
total_versions : int
    Total count of versions
 */
export interface ParameterHistoryResponse {
  parameter_name: string;
  qid: string;
  versions: ParameterVersionResponse[];
  total_versions: number;
}
