/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ParameterChangeResponseValue } from "./parameterChangeResponseValue";
import type { ParameterChangeResponsePreviousValue } from "./parameterChangeResponsePreviousValue";
import type { ParameterChangeResponseDelta } from "./parameterChangeResponseDelta";
import type { ParameterChangeResponseDeltaPercent } from "./parameterChangeResponseDeltaPercent";
import type { ParameterChangeResponseValidFrom } from "./parameterChangeResponseValidFrom";
import type { ParameterChangeResponsePreviousError } from "./parameterChangeResponsePreviousError";

/**
 * Response model for a parameter change (with delta from previous version).

Attributes
----------
entity_id : str
    Unique identifier for this parameter version
parameter_name : str
    Name of the parameter
qid : str
    Qubit or coupling identifier
value : float | int | str
    Current value
previous_value : float | int | str | None
    Previous value (None if first version)
unit : str
    Physical unit
delta : float | None
    Numeric difference (value - previous_value)
delta_percent : float | None
    Percentage change ((value - previous) / previous * 100)
version : int
    Version number
valid_from : datetime | None
    When this version became valid
task_name : str
    Name of the task that produced this value
execution_id : str
    Execution that produced this value
error : float
    Measurement error/uncertainty for current value
previous_error : float | None
    Measurement error/uncertainty for previous value (if available)
 */
export interface ParameterChangeResponse {
  entity_id: string;
  parameter_name: string;
  qid?: string;
  value: ParameterChangeResponseValue;
  previous_value?: ParameterChangeResponsePreviousValue;
  unit?: string;
  delta?: ParameterChangeResponseDelta;
  delta_percent?: ParameterChangeResponseDeltaPercent;
  version: number;
  valid_from?: ParameterChangeResponseValidFrom;
  task_name?: string;
  execution_id?: string;
  error?: number;
  previous_error?: ParameterChangeResponsePreviousError;
}
