/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Password change request model.
 */
export interface PasswordChange {
  current_password: string;
  new_password: string;
}
