/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Password reset request model (admin only).
 */
export interface PasswordReset {
  username: string;
  new_password: string;
}
