/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { PolicyViolationResponse } from "./policyViolationResponse";

/**
 * Response model for a list of policy violations.
 */
export interface PolicyViolationsResponse {
  violations?: PolicyViolationResponse[];
  /** Total violations matching query */
  total_count?: number;
}
