/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { PolicyViolationResponseValue } from "./policyViolationResponseValue";
import type { PolicyViolationResponseValidFrom } from "./policyViolationResponseValidFrom";
import type { PolicyViolationResponseWarnThreshold } from "./policyViolationResponseWarnThreshold";
import type { PolicyViolationResponseMeasured } from "./policyViolationResponseMeasured";

/**
 * Response model for a policy violation on a current parameter version.
 */
export interface PolicyViolationResponse {
  entity_id: string;
  parameter_name: string;
  qid?: string;
  value: PolicyViolationResponseValue;
  unit?: string;
  error?: number;
  valid_from?: PolicyViolationResponseValidFrom;
  /** warn */
  severity: string;
  /** min|max|staleness_hours|uncertainty_ratio */
  check_type: string;
  message?: string;
  warn_threshold?: PolicyViolationResponseWarnThreshold;
  measured?: PolicyViolationResponseMeasured;
}
