/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Position of the qubit on the device.
 */
export interface Position {
  x: number;
  y: number;
}
