/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectUpdateName } from "./projectUpdateName";
import type { ProjectUpdateDescription } from "./projectUpdateDescription";
import type { ProjectUpdateTags } from "./projectUpdateTags";
import type { ProjectUpdateDefaultRole } from "./projectUpdateDefaultRole";

/**
 * Request schema for updating a project.
 */
export interface ProjectUpdate {
  /** Project display name */
  name?: ProjectUpdateName;
  /** Project description */
  description?: ProjectUpdateDescription;
  /** Project tags */
  tags?: ProjectUpdateTags;
  /** Default role for new members */
  default_role?: ProjectUpdateDefaultRole;
}
