/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectRole } from "./projectRole";

/**
 * Default role for new members
 */
export type ProjectUpdateDefaultRole = ProjectRole | null;
