/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectCreateDescription } from "./projectCreateDescription";

/**
 * Request schema for creating a new project.
 */
export interface ProjectCreate {
  /**
   * Project display name
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** Project description */
  description?: ProjectCreateDescription;
  /** Project tags */
  tags?: string[];
}
