/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectListItemDescription } from "./projectListItemDescription";
import type { ProjectListItemCreatedAt } from "./projectListItemCreatedAt";

/**
 * Project summary for admin list view.
 */
export interface ProjectListItem {
  project_id: string;
  name: string;
  owner_username: string;
  description?: ProjectListItemDescription;
  member_count?: number;
  created_at?: ProjectListItemCreatedAt;
}
