/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectResponseDescription } from "./projectResponseDescription";
import type { ProjectRole } from "./projectRole";

/**
 * Response schema for project information.
 */
export interface ProjectResponse {
  project_id: string;
  owner_username: string;
  name: string;
  description: ProjectResponseDescription;
  tags: string[];
  default_role: ProjectRole;
  created_at: string;
  updated_at: string;
}
