/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Role of a member inside a project.

Simplified model:
- OWNER: Full access to project (read, write, admin)
- VIEWER: Read-only access (for invited members)
 */
export type ProjectRole = (typeof ProjectRole)[keyof typeof ProjectRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectRole = {
  owner: "owner",
  viewer: "viewer",
} as const;
