/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProvenanceStatsResponseRelationCounts } from "./provenanceStatsResponseRelationCounts";
import type { ParameterVersionResponse } from "./parameterVersionResponse";

/**
 * Response model for provenance statistics.

Attributes
----------
total_entities : int
    Total number of parameter versions
total_activities : int
    Total number of activity records
total_relations : int
    Total number of provenance relations
relation_counts : dict[str, int]
    Count by relation type
recent_entities : list[ParameterVersionResponse]
    Most recently created entities
 */
export interface ProvenanceStatsResponse {
  /** Total parameter versions */
  total_entities: number;
  /** Total activity records */
  total_activities: number;
  /** Total provenance relations */
  total_relations: number;
  /** Count by relation type */
  relation_counts?: ProvenanceStatsResponseRelationCounts;
  /** Recent entities */
  recent_entities?: ParameterVersionResponse[];
}
