/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Count by relation type
 */
export type ProvenanceStatsResponseRelationCounts = { [key: string]: number };
