/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectListItem } from "./projectListItem";

/**
 * Response containing list of all projects.
 */
export interface QdashApiSchemasAdminProjectListResponse {
  projects: ProjectListItem[];
  total: number;
}
