/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { MetricHistoryItem } from "./metricHistoryItem";

/**
 * Historical metric data for a single qubit.
 */
export interface QubitMetricHistoryResponse {
  chip_id: string;
  qid: string;
  metric_name: string;
  username: string;
  history: MetricHistoryItem[];
}
