/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Gate duration of the qubit.
 */
export interface QubitGateDuration {
  rz: number;
  sx: number;
  x: number;
}
