/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { Position } from "./position";
import type { MeasError } from "./measError";
import type { QubitLifetime } from "./qubitLifetime";
import type { QubitGateDuration } from "./qubitGateDuration";

/**
 * Qubit information.
 */
export interface Qubit {
  id: number;
  physical_id: number;
  position: Position;
  fidelity: number;
  meas_error: MeasError;
  qubit_lifetime: QubitLifetime;
  gate_duration: QubitGateDuration;
}
