/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Qubit lifetime of the qubit.
 */
export interface QubitLifetime {
  t1: number;
  t2: number;
}
