/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { QubitResponseData } from "./qubitResponseData";

/**
 * Response model for a single qubit.
 */
export interface QubitResponse {
  qid: string;
  chip_id: string;
  status?: string;
  data?: QubitResponseData;
}
