/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { RecommendedTaskResponse } from "./recommendedTaskResponse";

/**
 * Response model for recalibration recommendations.

When a parameter changes, this response provides a prioritized list
of calibration tasks that should be re-run to maintain consistency.

Attributes
----------
source_entity_id : str
    The changed parameter that triggered recommendations
source_parameter_name : str
    Name of the changed parameter
source_qid : str
    Qubit/coupling ID of the changed parameter
recommended_tasks : list[RecommendedTaskResponse]
    Prioritized list of tasks to re-run
total_affected_parameters : int
    Total count of downstream parameters affected
max_depth_reached : int
    Depth of impact graph traversed
 */
export interface RecalibrationRecommendationResponse {
  /** Changed parameter entity ID */
  source_entity_id: string;
  /** Changed parameter name */
  source_parameter_name?: string;
  /** Changed parameter QID */
  source_qid?: string;
  /** Prioritized task recommendations */
  recommended_tasks?: RecommendedTaskResponse[];
  /** Total downstream parameters affected */
  total_affected_parameters?: number;
  /** Impact graph depth traversed */
  max_depth_reached?: number;
}
