/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExecutionIdResponse } from "./executionIdResponse";

/**
 * Response model for recent execution IDs.

Attributes
----------
executions : list[ExecutionIdResponse]
    List of recent execution IDs sorted by most recent first
 */
export interface RecentExecutionsResponse {
  /** Recent execution IDs */
  executions?: ExecutionIdResponse[];
}
