/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ParameterChangeResponse } from "./parameterChangeResponse";

/**
 * Response model for recent parameter changes.

Attributes
----------
changes : list[ParameterChangeResponse]
    List of recent parameter changes with delta
total_count : int
    Total number of changes in the time window
 */
export interface RecentChangesResponse {
  /** Recent parameter changes */
  changes?: ParameterChangeResponse[];
  /** Total changes in time window */
  total_count?: number;
}
