/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response model for a recommended recalibration task.

Attributes
----------
task_name : str
    Name of the task to re-run
priority : int
    Priority level (1=highest, larger=lower priority)
affected_parameters : list[str]
    Parameters that would be recalibrated by this task
affected_qids : list[str]
    Qubit/coupling IDs affected
reason : str
    Human-readable explanation
 */
export interface RecommendedTaskResponse {
  /** Name of the task to re-run */
  task_name: string;
  /** Priority (1=highest) */
  priority: number;
  /** Parameters affected */
  affected_parameters?: string[];
  /** Qubit IDs affected */
  affected_qids?: string[];
  /** Explanation for recommendation */
  reason?: string;
}
