/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ReExecutionEntryStartAt } from "./reExecutionEntryStartAt";

/**
 * A child task result created by re-execution.
 */
export interface ReExecutionEntry {
  task_id: string;
  task_name: string;
  qid: string;
  status: string;
  start_at?: ReExecutionEntryStartAt;
}
