/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Default run parameters applied to all tasks (e.g., interval, shots)
 */
export type SaveFlowRequestDefaultRunParameters = { [key: string]: unknown };
