/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Entry point function name (defaults to same as name if not provided)
 */
export type SaveFlowRequestFlowFunctionName = string | null;
