/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { SaveFlowRequestFlowFunctionName } from "./saveFlowRequestFlowFunctionName";
import type { SaveFlowRequestDefaultParameters } from "./saveFlowRequestDefaultParameters";
import type { SaveFlowRequestDefaultRunParameters } from "./saveFlowRequestDefaultRunParameters";

/**
 * Request to save a Flow.
 */
export interface SaveFlowRequest {
  /** Flow name (alphanumeric + underscore only) */
  name: string;
  /** Flow description */
  description?: string;
  /** Python code content */
  code: string;
  /** Entry point function name (defaults to same as name if not provided) */
  flow_function_name?: SaveFlowRequestFlowFunctionName;
  /** Target chip ID */
  chip_id: string;
  /** Default execution parameters */
  default_parameters?: SaveFlowRequestDefaultParameters;
  /** Default run parameters applied to all tasks (e.g., interval, shots) */
  default_run_parameters?: SaveFlowRequestDefaultRunParameters;
  /** Tags for categorization */
  tags?: string[];
}
