/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response after saving a flow.
 */
export interface SaveFlowResponse {
  /** Flow name */
  name: string;
  /** Path to saved file */
  file_path: string;
  /** Success message */
  message: string;
}
