/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Request model for saving task file content.
 */
export interface SaveTaskFileRequest {
  path: string;
  content: string;
}
