/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * One-time execution time (ISO format, JST)
 */
export type ScheduleFlowRequestScheduledTime = string | null;
