/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ScheduleFlowRequestCron } from "./scheduleFlowRequestCron";
import type { ScheduleFlowRequestScheduledTime } from "./scheduleFlowRequestScheduledTime";
import type { ScheduleFlowRequestParameters } from "./scheduleFlowRequestParameters";

/**
 * Request to schedule a Flow execution.
 */
export interface ScheduleFlowRequest {
  /** Cron expression (e.g., '0 2 * * *' for daily at 2am JST) */
  cron?: ScheduleFlowRequestCron;
  /** One-time execution time (ISO format, JST) */
  scheduled_time?: ScheduleFlowRequestScheduledTime;
  /** Execution parameters (overrides default_parameters) */
  parameters?: ScheduleFlowRequestParameters;
  /** Whether the schedule is active */
  active?: boolean;
  /** Timezone for schedule */
  timezone?: string;
}
