/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Cron expression (e.g., '0 2 * * *' for daily at 2am JST)
 */
export type ScheduleFlowRequestCron = string | null;
