/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ScheduleFlowResponseCron } from "./scheduleFlowResponseCron";
import type { ScheduleFlowResponseNextRun } from "./scheduleFlowResponseNextRun";

/**
 * Response after scheduling a flow.
 */
export interface ScheduleFlowResponse {
  /** Schedule ID (deployment ID for cron, flow_run_id for one-time) */
  schedule_id: string;
  /** Flow name */
  flow_name: string;
  /** Schedule type: 'cron' or 'one-time' */
  schedule_type: string;
  /** Cron expression (for cron schedules) */
  cron?: ScheduleFlowResponseCron;
  /** Next scheduled run time */
  next_run?: ScheduleFlowResponseNextRun;
  /** Whether the schedule is active */
  active: boolean;
  /** Success message */
  message: string;
}
