/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { SeedImportRequestManualDataAnyOf } from "./seedImportRequestManualDataAnyOf";

/**
 * Manual data when source is MANUAL
 */
export type SeedImportRequestManualData =
  SeedImportRequestManualDataAnyOf | null;
