/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Source of seed parameters.
 */
export type SeedImportSource =
  (typeof SeedImportSource)[keyof typeof SeedImportSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeedImportSource = {
  qubex_params: "qubex_params",
  manual: "manual",
} as const;
