/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { SeedImportResultItemValue } from "./seedImportResultItemValue";
import type { SeedImportResultItemMessage } from "./seedImportResultItemMessage";

/**
 * Result for a single parameter import.
 */
export interface SeedImportResultItem {
  parameter_name: string;
  qid: string;
  value: SeedImportResultItemValue;
  unit: string;
  /** 'imported' or 'skipped' or 'error' */
  status: string;
  message?: SeedImportResultItemMessage;
}
