/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { SeedImportSource } from "./seedImportSource";
import type { SeedImportRequestParameters } from "./seedImportRequestParameters";
import type { SeedImportRequestQids } from "./seedImportRequestQids";
import type { SeedImportRequestManualData } from "./seedImportRequestManualData";

/**
 * Request to import seed parameters from qubex or manual input.

Attributes
----------
chip_id : str
    Target chip ID (e.g., "64Qv3")
source : SeedImportSource
    Source of the parameters
parameters : list[str] | None
    List of parameter names to import. If None, imports all available.
qids : list[str] | None
    List of qubit IDs to import. If None, imports all available.
manual_data : dict[str, dict[str, Any]] | None
    Manual data when source is MANUAL.
    Format: {"parameter_name": {"Q0": value, "Q1": value, ...}}
 */
export interface SeedImportRequest {
  /** Target chip ID */
  chip_id: string;
  /** Source of parameters */
  source?: SeedImportSource;
  /** Parameter names to import (None = all available) */
  parameters?: SeedImportRequestParameters;
  /** Qubit IDs to import (None = all available) */
  qids?: SeedImportRequestQids;
  /** Manual data when source is MANUAL */
  manual_data?: SeedImportRequestManualData;
}
