/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Settings for the QDash application.
 */
export interface Settings {
  env: string;
  client_url?: string;
  prefect_api_url: string;
  slack_bot_token?: string;
  slack_channel_id?: string;
  postgres_data_path: string;
  mongo_data_path: string;
  calib_data_path: string;
  mongo_db_name?: string;
  mongo_port?: number;
  mongo_express_port?: number;
  postgres_port?: number;
  prefect_port?: number;
  api_port?: number;
  ui_port?: number;
  log_level?: string;
  timezone?: string;
}
