/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * System-level role for a user.

ADMIN: Full system access, can manage all users and projects.
USER: Regular user.
 */
export type SystemRole = (typeof SystemRole)[keyof typeof SystemRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SystemRole = {
  admin: "admin",
  user: "user",
} as const;
