/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskFileSettingsDefaultBackend } from "./taskFileSettingsDefaultBackend";
import type { TaskFileSettingsDefaultViewMode } from "./taskFileSettingsDefaultViewMode";
import type { TaskFileSettingsSortOrder } from "./taskFileSettingsSortOrder";

/**
 * Task file settings model.
 */
export interface TaskFileSettings {
  default_backend?: TaskFileSettingsDefaultBackend;
  default_view_mode?: TaskFileSettingsDefaultViewMode;
  sort_order?: TaskFileSettingsSortOrder;
}
