/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskTaskId } from "./taskTaskId";
import type { TaskQid } from "./taskQid";
import type { TaskUpstreamId } from "./taskUpstreamId";
import type { TaskMessage } from "./taskMessage";
import type { TaskInputParameters } from "./taskInputParameters";
import type { TaskOutputParameters } from "./taskOutputParameters";
import type { TaskOutputParameterNames } from "./taskOutputParameterNames";
import type { TaskRunParameters } from "./taskRunParameters";
import type { TaskNote } from "./taskNote";
import type { TaskFigurePath } from "./taskFigurePath";
import type { TaskJsonFigurePath } from "./taskJsonFigurePath";
import type { TaskRawDataPath } from "./taskRawDataPath";
import type { TaskStartAt } from "./taskStartAt";
import type { TaskEndAt } from "./taskEndAt";
import type { TaskElapsedTime } from "./taskElapsedTime";
import type { TaskTaskType } from "./taskTaskType";

/**
 * Task is a Pydantic model that represents a task.
 */
export interface Task {
  task_id?: TaskTaskId;
  qid?: TaskQid;
  name?: string;
  upstream_id?: TaskUpstreamId;
  status?: string;
  message?: TaskMessage;
  input_parameters?: TaskInputParameters;
  output_parameters?: TaskOutputParameters;
  output_parameter_names?: TaskOutputParameterNames;
  run_parameters?: TaskRunParameters;
  note?: TaskNote;
  figure_path?: TaskFigurePath;
  json_figure_path?: TaskJsonFigurePath;
  raw_data_path?: TaskRawDataPath;
  start_at?: TaskStartAt;
  end_at?: TaskEndAt;
  elapsed_time?: TaskElapsedTime;
  task_type?: TaskTaskType;
  default_view?: boolean;
}
