/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { FileNodeType } from "./fileNodeType";
import type { TaskFileTreeNodeChildren } from "./taskFileTreeNodeChildren";

/**
 * Task file tree node model.
 */
export interface TaskFileTreeNode {
  name: string;
  path: string;
  type: FileNodeType;
  children?: TaskFileTreeNodeChildren;
}
