/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { ExpectedResultResponse } from "./expectedResultResponse";
import type { FailureModeResponse } from "./failureModeResponse";
import type { OutputParameterInfoResponse } from "./outputParameterInfoResponse";
import type { KnowledgeImageResponse } from "./knowledgeImageResponse";
import type { KnowledgeCaseResponse } from "./knowledgeCaseResponse";

/**
 * Response model for task knowledge (LLM-oriented domain knowledge).
 */
export interface TaskKnowledgeResponse {
  name: string;
  category?: string;
  summary: string;
  what_it_measures: string;
  physical_principle: string;
  expected_result: ExpectedResultResponse;
  evaluation_criteria: string;
  check_questions?: string[];
  failure_modes: FailureModeResponse[];
  tips: string[];
  output_parameters_info?: OutputParameterInfoResponse[];
  analysis_guide?: string[];
  prerequisites?: string[];
  images?: KnowledgeImageResponse[];
  cases?: KnowledgeCaseResponse[];
  prompt_text: string;
}
