/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskResponseBackend } from "./taskResponseBackend";
import type { TaskResponseInputParameters } from "./taskResponseInputParameters";
import type { TaskResponseOutputParameters } from "./taskResponseOutputParameters";

/**
 * Response model for a task.
 */
export interface TaskResponse {
  name: string;
  description: string;
  backend?: TaskResponseBackend;
  task_type: string;
  input_parameters: TaskResponseInputParameters;
  output_parameters: TaskResponseOutputParameters;
}
