/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TaskResultTaskId } from "./taskResultTaskId";
import type { TaskResultQid } from "./taskResultQid";
import type { TaskResultUpstreamId } from "./taskResultUpstreamId";
import type { TaskResultMessage } from "./taskResultMessage";
import type { TaskResultInputParameters } from "./taskResultInputParameters";
import type { TaskResultOutputParameters } from "./taskResultOutputParameters";
import type { TaskResultOutputParameterNames } from "./taskResultOutputParameterNames";
import type { TaskResultRunParameters } from "./taskResultRunParameters";
import type { TaskResultNote } from "./taskResultNote";
import type { TaskResultFigurePath } from "./taskResultFigurePath";
import type { TaskResultJsonFigurePath } from "./taskResultJsonFigurePath";
import type { TaskResultRawDataPath } from "./taskResultRawDataPath";
import type { TaskResultStartAt } from "./taskResultStartAt";
import type { TaskResultEndAt } from "./taskResultEndAt";
import type { TaskResultElapsedTime } from "./taskResultElapsedTime";
import type { TaskResultTaskType } from "./taskResultTaskType";

/**
 * TaskResult is a Pydantic model that represents a task result.
 */
export interface TaskResult {
  task_id?: TaskResultTaskId;
  qid?: TaskResultQid;
  name?: string;
  upstream_id?: TaskResultUpstreamId;
  status?: string;
  message?: TaskResultMessage;
  input_parameters?: TaskResultInputParameters;
  output_parameters?: TaskResultOutputParameters;
  output_parameter_names?: TaskResultOutputParameterNames;
  run_parameters?: TaskResultRunParameters;
  note?: TaskResultNote;
  figure_path?: TaskResultFigurePath;
  json_figure_path?: TaskResultJsonFigurePath;
  raw_data_path?: TaskResultRawDataPath;
  start_at?: TaskResultStartAt;
  end_at?: TaskResultEndAt;
  elapsed_time?: TaskResultElapsedTime;
  task_type?: TaskResultTaskType;
  default_view?: boolean;
}
