/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Summary response for list endpoint (no heavy fields).
 */
export interface TaskKnowledgeSummaryResponse {
  name: string;
  category?: string;
  summary: string;
  failure_mode_count?: number;
  case_count?: number;
  image_count?: number;
  has_analysis_guide?: boolean;
}
