/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { TokenResponseDefaultProjectId } from "./tokenResponseDefaultProjectId";

/**
 * Token response model for login.
 */
export interface TokenResponse {
  access_token: string;
  token_type?: string;
  username: string;
  default_project_id?: TokenResponseDefaultProjectId;
}
