/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UITaskFilesSettingsDefaultBackend } from "./uITaskFilesSettingsDefaultBackend";
import type { UITaskFilesSettingsDefaultViewMode } from "./uITaskFilesSettingsDefaultViewMode";
import type { UITaskFilesSettingsSortOrder } from "./uITaskFilesSettingsSortOrder";

/**
 * Task files editor settings.
 */
export interface UITaskFilesSettings {
  default_backend?: UITaskFilesSettingsDefaultBackend;
  default_view_mode?: UITaskFilesSettingsDefaultViewMode;
  sort_order?: UITaskFilesSettingsSortOrder;
}
