/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Response for updating a schedule.
 */
export interface UpdateScheduleResponse {
  /** Success message */
  message: string;
  /** Updated schedule ID */
  schedule_id: string;
}
