/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateUserRequestFullName } from "./updateUserRequestFullName";
import type { UpdateUserRequestDisabled } from "./updateUserRequestDisabled";
import type { UpdateUserRequestSystemRole } from "./updateUserRequestSystemRole";

/**
 * Request to update user settings (admin only).
 */
export interface UpdateUserRequest {
  full_name?: UpdateUserRequestFullName;
  disabled?: UpdateUserRequestDisabled;
  system_role?: UpdateUserRequestSystemRole;
}
