/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateScheduleRequestCron } from "./updateScheduleRequestCron";
import type { UpdateScheduleRequestParameters } from "./updateScheduleRequestParameters";

/**
 * Request to update a schedule.
 */
export interface UpdateScheduleRequest {
  /** Whether the schedule is active */
  active: boolean;
  /** Updated cron expression (optional) */
  cron?: UpdateScheduleRequestCron;
  /** Updated parameters (optional) */
  parameters?: UpdateScheduleRequestParameters;
  /** Timezone for cron schedule */
  timezone?: string;
}
