/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserDetailResponseFullName } from "./userDetailResponseFullName";
import type { SystemRole } from "./systemRole";
import type { UserDetailResponseDefaultProjectId } from "./userDetailResponseDefaultProjectId";
import type { UserDetailResponseCreatedAt } from "./userDetailResponseCreatedAt";
import type { UserDetailResponseUpdatedAt } from "./userDetailResponseUpdatedAt";

/**
 * Detailed user response for admin view.
 */
export interface UserDetailResponse {
  username: string;
  full_name?: UserDetailResponseFullName;
  disabled?: boolean;
  system_role?: SystemRole;
  default_project_id?: UserDetailResponseDefaultProjectId;
  created_at?: UserDetailResponseCreatedAt;
  updated_at?: UserDetailResponseUpdatedAt;
}
