/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserCreateFullName } from "./userCreateFullName";

/**
 * User creation model for registration (admin only).
 */
export interface UserCreate {
  username: string;
  password: string;
  full_name?: UserCreateFullName;
}
