/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserWithTokenFullName } from "./userWithTokenFullName";
import type { UserWithTokenDisabled } from "./userWithTokenDisabled";
import type { UserWithTokenDefaultProjectId } from "./userWithTokenDefaultProjectId";
import type { SystemRole } from "./systemRole";

/**
 * User model with access token for login/register responses.
 */
export interface UserWithToken {
  username: string;
  full_name?: UserWithTokenFullName;
  disabled?: UserWithTokenDisabled;
  default_project_id?: UserWithTokenDefaultProjectId;
  system_role?: SystemRole;
  access_token: string;
}
