/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserListItemFullName } from "./userListItemFullName";
import type { SystemRole } from "./systemRole";
import type { UserListItemDefaultProjectId } from "./userListItemDefaultProjectId";

/**
 * User summary for admin list view.
 */
export interface UserListItem {
  username: string;
  full_name?: UserListItemFullName;
  disabled?: boolean;
  system_role?: SystemRole;
  default_project_id?: UserListItemDefaultProjectId;
}
