/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import type { UserFullName } from "./userFullName";
import type { UserDisabled } from "./userDisabled";
import type { UserDefaultProjectId } from "./userDefaultProjectId";
import type { SystemRole } from "./systemRole";

/**
 * User model for authentication and user management.
 */
export interface User {
  username: string;
  full_name?: UserFullName;
  disabled?: UserDisabled;
  default_project_id?: UserDefaultProjectId;
  system_role?: SystemRole;
}
