/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */

/**
 * Request model for validating file content.
 */
export interface ValidateFileRequest {
  content: string;
  file_type: string;
}
