/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * QDash API
 * API for QDash
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CancelExecutionResponse,
  Detail,
  ExecuteFlowResponse,
  ExecutionLockStatusResponse,
  ExecutionResponseDetail,
  GetFigureByPathParams,
  HTTPValidationError,
  ListExecutionsParams,
  ListExecutionsResponse,
  ReExecuteRequest,
} from "../../schemas";

import { customInstance } from "../../lib/custom-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Fetch a calibration figure by its file path.

Retrieves a PNG image file from the server's filesystem and returns it
as a streaming response.

Parameters
----------
path : str
    Absolute file path to the calibration figure image

Returns
-------
FileResponse
    PNG image data as a file response with media type "image/png"

Raises
------
HTTPException
    404 if the file does not exist at the specified path
 * @summary Get a calibration figure by its path
 */
export const getFigureByPath = (
  params: GetFigureByPathParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/executions/figure`, method: "GET", params, signal },
    options,
  );
};

export const getGetFigureByPathQueryKey = (params?: GetFigureByPathParams) => {
  return [`/executions/figure`, ...(params ? [params] : [])] as const;
};

export const getGetFigureByPathQueryOptions = <
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = Detail | HTTPValidationError,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFigureByPathQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFigureByPath>>> = ({
    signal,
  }) => getFigureByPath(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFigureByPath>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetFigureByPathQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFigureByPath>>
>;
export type GetFigureByPathQueryError = Detail | HTTPValidationError;

export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = Detail | HTTPValidationError,
>(
  params: GetFigureByPathParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFigureByPath>>,
          TError,
          Awaited<ReturnType<typeof getFigureByPath>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = Detail | HTTPValidationError,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFigureByPath>>,
          TError,
          Awaited<ReturnType<typeof getFigureByPath>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = Detail | HTTPValidationError,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get a calibration figure by its path
 */

export function useGetFigureByPath<
  TData = Awaited<ReturnType<typeof getFigureByPath>>,
  TError = Detail | HTTPValidationError,
>(
  params: GetFigureByPathParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFigureByPath>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetFigureByPathQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch the current status of the execution lock.

The execution lock prevents concurrent calibration workflows from running
simultaneously. This endpoint checks whether a lock is currently held.

Parameters
----------
ctx : ProjectContext
    Project context with user and project information
execution_service : ExecutionService
    Service for execution operations

Returns
-------
ExecutionLockStatusResponse
    Response containing lock status (True if locked, False if available)
 * @summary Get the execution lock status
 */
export const getExecutionLockStatus = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecutionLockStatusResponse>(
    { url: `/executions/lock-status`, method: "GET", signal },
    options,
  );
};

export const getGetExecutionLockStatusQueryKey = () => {
  return [`/executions/lock-status`] as const;
};

export const getGetExecutionLockStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = HTTPValidationError,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getExecutionLockStatus>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExecutionLockStatusQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getExecutionLockStatus>>
  > = ({ signal }) => getExecutionLockStatus(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getExecutionLockStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetExecutionLockStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExecutionLockStatus>>
>;
export type GetExecutionLockStatusQueryError = HTTPValidationError;

export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = HTTPValidationError,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionLockStatus>>,
          TError,
          Awaited<ReturnType<typeof getExecutionLockStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecutionLockStatus>>,
          TError,
          Awaited<ReturnType<typeof getExecutionLockStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get the execution lock status
 */

export function useGetExecutionLockStatus<
  TData = Awaited<ReturnType<typeof getExecutionLockStatus>>,
  TError = HTTPValidationError,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getExecutionLockStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetExecutionLockStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * List executions for a given chip with pagination.

Parameters
----------
ctx : ProjectContext
    Project context with user and project information
execution_service : ExecutionService
    Service for execution operations
chip_id : str
    ID of the chip to fetch executions for
skip : int
    Number of items to skip (default: 0)
limit : int
    Number of items to return (default: 20, max: 100)

Returns
-------
ListExecutionsResponse
    Wrapped list of executions for the chip
 * @summary List executions
 */
export const listExecutions = (
  params: ListExecutionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ListExecutionsResponse>(
    { url: `/executions`, method: "GET", params, signal },
    options,
  );
};

export const getListExecutionsQueryKey = (params?: ListExecutionsParams) => {
  return [`/executions`, ...(params ? [params] : [])] as const;
};

export const getListExecutionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = HTTPValidationError,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListExecutionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listExecutions>>> = ({
    signal,
  }) => listExecutions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listExecutions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListExecutionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listExecutions>>
>;
export type ListExecutionsQueryError = HTTPValidationError;

export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = HTTPValidationError,
>(
  params: ListExecutionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutions>>,
          TError,
          Awaited<ReturnType<typeof listExecutions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = HTTPValidationError,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExecutions>>,
          TError,
          Awaited<ReturnType<typeof listExecutions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = HTTPValidationError,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List executions
 */

export function useListExecutions<
  TData = Awaited<ReturnType<typeof listExecutions>>,
  TError = HTTPValidationError,
>(
  params: ListExecutionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listExecutions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListExecutionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Return the execution detail by its ID.

Parameters
----------
execution_id : str
    ID of the execution to fetch
ctx : ProjectContext
    Project context with user and project information
execution_service : ExecutionService
    Service for execution operations

Returns
-------
ExecutionResponseDetail
    Detailed execution information
 * @summary Get an execution by its ID
 */
export const getExecution = (
  executionId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecutionResponseDetail>(
    { url: `/executions/${executionId}`, method: "GET", signal },
    options,
  );
};

export const getGetExecutionQueryKey = (executionId?: string) => {
  return [`/executions/${executionId}`] as const;
};

export const getGetExecutionQueryOptions = <
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = HTTPValidationError,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetExecutionQueryKey(executionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getExecution>>> = ({
    signal,
  }) => getExecution(executionId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!executionId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getExecution>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetExecutionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getExecution>>
>;
export type GetExecutionQueryError = HTTPValidationError;

export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = HTTPValidationError,
>(
  executionId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecution>>,
          TError,
          Awaited<ReturnType<typeof getExecution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = HTTPValidationError,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExecution>>,
          TError,
          Awaited<ReturnType<typeof getExecution>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = HTTPValidationError,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get an execution by its ID
 */

export function useGetExecution<
  TData = Awaited<ReturnType<typeof getExecution>>,
  TError = HTTPValidationError,
>(
  executionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getExecution>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetExecutionQueryOptions(executionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Cancel a running or scheduled execution via Prefect.

Sends a cancellation request to Prefect for the specified flow run.
The flow_run_id is the Prefect flow run UUID, which can be obtained from
the execution detail's note.flow_run_id field.
Only executions in SCHEDULED, PENDING, RUNNING, or PAUSED state can be cancelled.

Parameters
----------
flow_run_id : str
    Prefect flow run UUID
ctx : ProjectContext
    Project context with user and project information
execution_service : ExecutionService
    Service for execution operations

Returns
-------
CancelExecutionResponse
    Cancellation result with status
 * @summary Cancel a running or scheduled execution
 */
export const cancelExecution = (
  flowRunId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CancelExecutionResponse>(
    { url: `/executions/${flowRunId}/cancel`, method: "POST", signal },
    options,
  );
};

export const getCancelExecutionMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelExecution>>,
    TError,
    { flowRunId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelExecution>>,
  TError,
  { flowRunId: string },
  TContext
> => {
  const mutationKey = ["cancelExecution"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelExecution>>,
    { flowRunId: string }
  > = (props) => {
    const { flowRunId } = props ?? {};

    return cancelExecution(flowRunId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelExecutionMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelExecution>>
>;

export type CancelExecutionMutationError = HTTPValidationError;

/**
 * @summary Cancel a running or scheduled execution
 */
export const useCancelExecution = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelExecution>>,
      TError,
      { flowRunId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelExecution>>,
  TError,
  { flowRunId: string },
  TContext
> => {
  const mutationOptions = getCancelExecutionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Re-execute a flow using snapshot parameters from a previous execution.

Parameters
----------
execution_id : str
    ID of the source execution to snapshot parameters from
request : ReExecuteRequest
    Re-execution request with flow_name and optional parameter_overrides
ctx : ProjectContext
    Project context with user and project information
execution_service : ExecutionService
    Service for execution operations
flow_service : FlowService
    Service for flow operations

Returns
-------
ExecuteFlowResponse
    Execution result with IDs and URLs
 * @summary Re-execute a flow from snapshot parameters
 */
export const reExecuteFromSnapshot = (
  executionId: string,
  reExecuteRequest: ReExecuteRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ExecuteFlowResponse>(
    {
      url: `/executions/${executionId}/re-execute`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: reExecuteRequest,
      signal,
    },
    options,
  );
};

export const getReExecuteFromSnapshotMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reExecuteFromSnapshot>>,
    TError,
    { executionId: string; data: ReExecuteRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reExecuteFromSnapshot>>,
  TError,
  { executionId: string; data: ReExecuteRequest },
  TContext
> => {
  const mutationKey = ["reExecuteFromSnapshot"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reExecuteFromSnapshot>>,
    { executionId: string; data: ReExecuteRequest }
  > = (props) => {
    const { executionId, data } = props ?? {};

    return reExecuteFromSnapshot(executionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReExecuteFromSnapshotMutationResult = NonNullable<
  Awaited<ReturnType<typeof reExecuteFromSnapshot>>
>;
export type ReExecuteFromSnapshotMutationBody = ReExecuteRequest;
export type ReExecuteFromSnapshotMutationError = HTTPValidationError;

/**
 * @summary Re-execute a flow from snapshot parameters
 */
export const useReExecuteFromSnapshot = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reExecuteFromSnapshot>>,
      TError,
      { executionId: string; data: ReExecuteRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reExecuteFromSnapshot>>,
  TError,
  { executionId: string; data: ReExecuteRequest },
  TContext
> => {
  const mutationOptions = getReExecuteFromSnapshotMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
